- configure
- examples/Makefile
- src/Makefile
When libsystemd is not installed on the system, then the pkg-config
check would still be true when systemd itself is on the system. Also,
when the library is unavailable then the hard-coded "-lsystemd" would
cause the build to fail. The following changes fix that.
* configure: changed check from "systemd" to the library "libsystemd"
* examples/Makefile: Replaced hard-coded "-lsystemd" with "${LDFLAGS}"
as defined by "config-host.mak" in examples/Makefile
* src/Makefile: added include of "config-host.mak", removed hard-coded
"-lsystemd", "-lsystemd" will trickle in from LDFLAGS
Signed-off-by: Simon A. F. Lund <simon.lund@samsung.com>
On my laptop (DebianBuster), it:
* Now builds with and without libsystemd
* ./test/test ran without error both with and without libsystemd
> Fix dependency on systemd

- src/nvme/ioctl.c
Used in nvme_get_log(), caused nvme_get_log_error() failures.
> ioctl: Fix NVME_LOG_CDW10_NUMDL_MASK

- src/nvme/ioctl.h
- src/nvme/types.h
Most strings are taken from the official NVMe specification document: https://nvmexpress.org/developers/nvme-specification/. Not sure what is the licensing and terms to reuse the strings.
Some annotation references like the `@enum nvme_xxx` may need fixing, as well as the hex constants annotations.
> Docs strings updates

- Makefile
Might be a matter of personal taste, however this comes handy when linking statically against an uninstalled source tree.
> build: Include libnvme.pc in the default make target

- src/nvme/tree.c
- src/nvme/tree.h
The 'address' string really are several parts (traddr, trsvcid, and
host_addr) which are separated by commas. So avoid every user having
to parse that string on its own this patch exposes the individual parts
via nvme_ctrl_get_{traddr,trsvcid,host_traddr}.
Each call might return NULL if the respective value isn't set.
> Parse 'address' string into components

- configure
- src/nvme/tree.c
- src/nvme/tree.h
Add configuration flags '--disable-systemd' and '--disable-uuid'
to forcibly exclude systemd and uuid during build.
> Make systemd and uuid optional

- src/nvme/fabrics.c
- src/nvme/tree.c
- src/nvme/util.c
PCIe devices do not necessarily have a hostnqn set, so use the
default hostnqn when looking up hosts.
And for PCIe devices the transport address is the entire 'address'
string, no parsing required.
> fabrics,tree: Fixes for PCIe devices

- src/nvme/fabrics.c
Fix string formatting of the uuid from systemd.
Fixes: 8999e3d9b218 ("fabrics: Read system UUID from DMI and merge hostnqn generation functions")
Signed-off-by: Klaus Jensen <k.jensen@samsung.com>
> nvme/fabrics: fix compile error

- src/nvme/libnvme.i
- src/nvme/private.h
- src/nvme/tree.c
The original idea of implementing refcounting turned out to be not really feasible, as without deep knowledge of SWIG and python internals it's not quite easy to see if and when refcounts would need to be acquired or dropped.
This has caused a SIGBUS error in the python interpreter when the example scripts are run.
So kill the entire refcounting idea and deallocate the internal tree on nvme_free_tree() _only_; that ensures that individual objects are always available and we don't have to worry about that.
It also means that the object deallocation methods liks nvme_free_ctrl() etc are now no-ops, and are kept purely for symmetry and to keep SWIG happy.
> Rework tree reallocation

- src/Makefile
- src/nvme/fabrics.c
- src/nvme/libnvme.i
- src/nvme/log.c
- src/nvme/log.h
- src/nvme/tree.c
- src/setup.py
This pull requests contains these items:
- Changes made by Hannes and me for improved logging
- A memory leak was fixed in the Python wrapper code (SWIG)
- The Python class names were renamed to simplify the syntax (before-and-after example below)
Python class renaming:
Before:
```
from libnvme import libnvme
root = libnvme.nvme_root()
host = libnvme.nvme_host(root)
ctrl = libnvme.nvme_ctrl(.....)
```
After:
```
from libnvme import nvme
root = nvme.root()
host = nvme.host(root)
ctrl = nvme.ctrl(.....)
```
> Improvements to Python bindings

- src/Makefile
- src/nvme/tree.c
Minor build fixes when `json-c` is disabled during `configure`.
The `nvme_update_config()` function doesn't make much sense in that case, returning an error instead.
> build: Fix build without json-c

- src/nvme/ioctl.h
- src/nvme/types.h
Doc strings update related to the device self-test log page retrieval and the self-test command issue.
Also proposing some API changes as included in this commit:
* renamed `NVME_ST_CODE_RESRVED` to `NVME_ST_CODE_RESERVED`
* added the `enum nvme_st_curr_op` definiton:
* while the `enum nvme_st_curr_op` and `enum nvme_st_code` struct members are mostly similar, the former relates to the current running operation within the `struct nvme_self_test_log` structure, the latter relates to finished test results. These two are also defined separately in the nvme standard whitepaper.
Feel free to align naming of the mentioned symbols to fit the library conventions, might be just mine interpretation of the nvme specs...
> types: Device self-test doc strings update

- configure
- examples/Makefile
- src/Makefile
- src/nvme/ioctl.c
- test/Makefile
This series includes a couple of compilation failures on my platform; the first for a link-order issue, the second for building c++ objects with plain `cc`. 
I've taken the approach of minimal change here; we may not need the full `$(LIBS)` on the `.so` link, but that's what the current build rules specify. Happy to update this if necessary.
> Minor fixes for a couple of compilation failures

- src/nvme/tree.c
When a controller returns an empty "model" attribute (ref. Identify PDU) default "model" to "undefined".
> Default empty model attribute to 'undefined'

- src/nvme/fabrics.c
This fixes:
```
nvme/fabrics.c:692:2: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
692 |  asprintf(&hostnqn, "nqn.2014-08.org.nvmexpress:uuid:%s\n", uuid_str);
|  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> Fix compiler warning

- src/Makefile
- src/nvme/filters.c
- src/nvme/filters.h
- src/nvme/private.h
- src/nvme/tree.c
Our tree structure host->subsys->ctrl doesn't match the underlying
topology; the subsystem actually just a container for controllers,
and the hosts are specified on the controller level, not the subsystem
level.
So to flatten that into our tree structure we need to duplicate the
subsystem objects for each host, and filter out the controllers such
that only the controllers with the correct hostnqn will show up
in our internal tree.
> tree: rework topology for multiple hosts

- src/nvme/tree.c
Function `nvme_free_ctrl()` was previously defined as an empty stub. Instead, we now allow `nvme_free_ctrl()` to delete ctrl objects by calling `__nvme_free_ctrl()`.
> Allow control objects to be deleted.

- src/nvme/fabrics.c
The recently added uuid_from_device_tree function can be refactored by
minimizing use of local variables and early returns in error
handling. No functional change.
> fabrics: Refactor uuid_from_device_tree

- src/nvme/ioctl.c
- src/nvme/ioctl.h
This patch fixes a bug in `nvme_identify_iocs` where the wrong CNS value used in
the Identify Command data structure.
Signed-off-by: Andreas Hindborg <andreas.hindborg@wdc.com>
> Fix bug in `nvme_identify_iocs`

- examples/Makefile
- src/nvme/tree.c
- src/nvme/util.c
- test/Makefile
Hi all,
I've found that 'test/cpp.cc' doesn't work on older kernels, for a variety of reasons:
- It'll crash on PCIe controllers, as older kernels don't provide an 'address' sysfs attribute
- It will only display a subset of the found controllers and paths, as C++ '<<' operator silently aborts the program (!)
if the called function returns 'NULL'.
With this patchset the 'cpp' program is fixed to return all informations.
> Scanning fixes

- src/nvme/fabrics.c
At @hreinecke's request, I am bringing this change from the nvme-cli repo (https://github.com/linux-nvme/nvme-cli/pull/1036).
[RFC4007](https://datatracker.ietf.org/doc/html/rfc4007) describes a way to specify IPv6 addresses with a scope as follows:
```
<ipv6-address>%<scope>
E.g.  fe80:aaaa:1807:5b9e:6be7:f38d%enp0s3
```
The '`%`' delimiter is used to separate the address from the scope. And the scope is used to identify an interface (e.g. `eth1`, `enp0s3`, etc). Linux supports this syntax. The `nvme-tcp` driver does too. However, `libnvme` strips the scope away from `TRADDR`. This pull requests fixes the issue and allows passing the scope to the `nvme-tcp` driver.
Note that the fix is inspired from code found in the `nvme-tcp` driver. Namely, the use of the API `inet_pton_with_scope()` …
> Add support for scoped IPv6 in TRADDR

- src/libnvme.map
- src/nvme/fabrics.c
- src/nvme/json.c
- src/nvme/private.h
- src/nvme/tree.c
- src/nvme/tree.h
Add a function 'nvme_dump_config()' which will print out the internal tree to stdout.
This is required to implement a 'dump-config' operation for nvme-cli, to print out the internal tree to stdout.
> Add 'nvme_dump_config()' function

- README.md
- configure
- meson.build
- meson_options.txt
- pynvme/setup.py
- src/meson.build
- src/nvme/fabrics.c
Commit 3e0520ecad13 ("Read system UUID from DMI and merge hostnqn
generation functions") in nvme-cli introduced the feature to create
the UUID derived from machine-id using the systemd's
sd_id128_get_machine_app_specific function. This adds many library
dependencies to libnvme.
The feature is not really necessary as we have nvme-gen-hostnqn
already in place. So drop the feature entirely.
If the feature needs to be added back, it's probably better to
reimplement this function (e.g. move the hmac_sha256 function from
nvme-cli and use this to derive the UUID from machine-id).
Fixes #62 
> fabrics: Remove 'UUID derived from machine-id' feature

- meson.build
- src/meson.build
meson has a very fancy feature called subproject. This allows bundle
third party libraries in a project. In order to be able to use this
for nvme-cli we need to drop all global config settings and declare
all dependencies.
> build: Allow subproject meson builds

- meson.build
Set minimum version for json-c to 0.13.
libnvme uses json_util_get_last_err() which got introduced in 0.13,
released in December 2017.
While at it, drop the cc.find_library() lookup logic. First, we don't
do this for libuuid and second, dependency() is using pkg-config to
figure out the dependency, thus we can set the minimum version
number. Instead, cc.find_library() will try to link a test program
with '-libjson-c' and have no way to figure out which version it
actually is. Avoid any confusion and make the meson.build script
simpler.
See also #65
> build: Set minimum version for json-c

- pynvme/nvme.i
Simplified Python exception handling. Removed unnecessary asserts.
> [Python]: Clean up exception handling

- meson.build
- src/Makefile
- src/meson.build
- src/nvme/json.c
meson supports embedded library build. This is very handy for system
which ship outdated an really outdated json-c library.
The include path for json.h has to be adapted. The json-c upstream
project is not clear which include prefix should be used ('#include
<json-c/json.h>" vs '#include <json.h>'. In order to support embedded
builds, we need to use the second version of the include. The source
code is added to the build, hence we use the include directory path of
the project layout. And json-c has all include files in the root
directory. This is no problem when using a installed version of json-c
as pkg-config adds '-I/usr/inlude/json-c' to the include paths:
$pkg-config --cflags json-c
-I/usr/include/json-c
So the simplest thing to support both build cased (external/embedded)
just drop …
> build: Add fallback dependency for json-c

- ccan/meson.build
- meson.build
- src/meson.build
We are missing the *.c files from the ccan code base in the build.
As we currently don't use any function implemented in the *.c files
all just works.
> ccan: Add *.c files to the build

- .github/workflows/meson.yml
- libnvme/meson.build
This is related to this issue:https://github.com/linux-nvme/libnvme/issues/90#issuecomment-957539757
When the CI tests are run from another project (i.e. `libnvme` is the subproject of another project, for example `nvme-cli`), then the Python tests are failing.
I'm not sure what the problem is exactly. I think it may have something to do with the `PYTHONPATH`. This patch uses a relative path instead of an absolute one to see if that will make a difference. 
I also changed the workflow script to collect the meson test log file on failure. This should give us more info in case of failure. 
> Fix python unit tests when run as a subproject of another project

- src/nvme/fabrics.c
Remove a duplicate read() statement. 
I checked with Hannes and he confirmed that the line was added by mistake.
> Remove a duplicate read() statement

- meson.build
- src/nvme/types.h
Mostly doc strings update, found typo in a constant name in between. Would be nice to run spell checker or something before the first public release.
Also removed the _'v'_ prefix from the library version number to align with the usual `pkg-config` file versioning practices.
> Docs updates + minor fixes

- doc/libnvme.rst
- doc/man/struct nvme_id_psd.2
- src/nvme/types.h
it used to be active_work_scale on nvme-cli, so rename it as apws (active power work & scale)
https://github.com/linux-nvme/nvme-cli/blob/nvme-cli-monolithic/linux/nvme.h#L258
> types: fix wrong bits nvme_id_psd apw[178:176], aps[183:182]

- doc/libnvme.rst
- doc/man/nvme_ctrl_get_nqn.2
- src/libnvme.map
- src/nvme/fabrics.c
Stale reference, function is not implemented.
> Remove references to nvme_ctrl_get_nqn()

- examples/discover-loop.c
- src/libnvme.map
- src/nvme/fabrics.c
- src/nvme/fabrics.h
- src/nvme/tree.c
'struct nvme_fabrics_config' has some default values, and the output
functions key off these values to filter the values being printed.
So to avoid applications having to know these default values this
patch introduces a function nvmf_default_config() to ensure that
every application is using the same defaults.
> fabrics: add nvmf_default_config()

- src/libnvme.map
Adding support for discovery controller discovery did not add
the new symbols to the map file.
> Add missing symbols for discovery to map file

- libnvme/nvme.i
- src/libnvme.map
Add discovery_ctrl_set() to Python bindings
Following Hannes' recent TP8013 changes, we need
to add this method to the Python bindings.
> Add discovery_ctrl_set() to Python bindings

- src/libnvme.map
- src/nvme/fabrics.h
Add some function documentation and the missing symbol nvmf_eflags_str
to the mapfile.
> fabrics: add missing function documentation and mapfile update

- src/libnvme.map
- src/nvme/private.h
- src/nvme/tree.c
- src/nvme/tree.h
Namespace device node is initialized into two different nodes: block
device and character device which is a generic device used when block
device is not available due to initialization failure in the kernel.
This can be directly retrieved from the `struct nvme_ns` to print out
the generic node in somewhere like `nvme list` command in nvme-cli.
Signed-off-by: Minwoo Im <minwoo.im.dev@gmail.com>
> tree: add namespace chrdev name to nvme_ns

- meson.build
- subprojects/json-c.wrap
Also rename config.h to libnvme-config.h as recommend by the meson documentation https://mesonbuild.com/Wrap-best-practices-and-tips.html#do-not-put-configh-in-external-search-path
> Update json c wrap

- ccan/meson.build
The default include paths are not set when building the configurator,
hence the build fails when libnvme is consumed by an project as wrap.
> build: Set include dirs when buidling configurator

- src/nvme/types.h
[root@ltczz405-lp2 nvme-cli]# ./nvme persistent-event-log -a 0 /dev/nvme0>out
[20748.494262] nvme[9059]: segfault (11) at 7fff8cf20007 nip 10024828 lr 10024824 code 2 in nvme[10000000+c0000]
[20748.494288] nvme[9059]: code: 3b9c0024 3b7b0001 4bfddb41 e8410018 889cffe6 7e439378 4bfddb31 e8410018
[20748.494295] nvme[9059]: code: 889cffe7 e8610068 4bfddb21 e8410018 <809cfff4> e8610070 4bfddb11 e8410018
Segmentation fault (core dumped)
Saw the segmentation fault. Also looks only the first event is good. Other events are like random stuff.
Persistent Event Log for device: nvme0
Action for Persistent Event Log: 0
Log Identifier: 13
Total Number of Events: 6963
Total Log Length : 674496
Log Revision: 1
Log Header Length: 492
Timestamp: 564586531692487
Power On Hours (POH): 5,576
Power Cycle …
> libnvme: core dump when running nvme persistent-event-log

- src/nvme/ioctl.c
- src/nvme/ioctl.h
- src/nvme/linux.c
- src/nvme/tree.c
- test/zns.c
There is quite some inconsistency as to whether the ioctl wrapper functions return the NVMe CQE result or whether they accept a timeout argument.
So this patchsets sanitizes the calling convention by always adding a timeout and result argument.
> RFC: Sanitize ioctl command wrappers

- src/nvme/tree.c
The attribute in `struct nvme_ns` is `generic_name`, not chrdev.  So
rename the function name of this attribute.
Signed-off-by: Minwoo Im <minwoo.im.dev@gmail.com>
> tree: rename namespace function name chrdev to generic

- libnvme/nvme.i
- src/libnvme.map
- src/nvme/fabrics.c
- src/nvme/json.c
- src/nvme/private.h
- src/nvme/tree.c
- src/nvme/tree.h
Implement a 'dhchap_key' attribute for the nvme_host structure to
support the 'dhchap_secret' connection argument, and a
'dhchap_key' attribute for the nvme_controller structure to support
the 'dhchap_ctrl_secret' connection argument.
Note: The kernel side is still under review, but the interface seems to have stabilized. So pulling it in now will help with testing.
> Implement 'dhchap_key' host and controller attributes

- src/nvme/ioctl.c
- src/nvme/ioctl.h
- test/zns.c
With the recent up the calling convention has been sanitzed to always
have the 'timeout' argument as second-to-last, and the 'result' as the
laster argument.
Modify the zns commands accordingly.
> Sanitize zns command arguments

- ccan/meson.build
- examples/meson.build
- libnvme/meson.build
- meson.build
- src/meson.build
- test/meson.build
meson does the feature detection itself and we don't have to rely on
the configurator. So don't use it.
> build: Do not use the configurator for meson

- src/nvme/fabrics.c
For a discovery log page entry that indicates the discovery controller
that returned it (i.e. itself), we need to set the controller as
discovered (because we got the discovery log page by connecting to it).
Without this connect-all goes in an endless loop keep connecting and
retrieving the log page from the same discovery subsystem port.
Fixes: 06a8f001d314 ("tree,fabrics: detect discovery loops")
Signed-off-by: Sagi Grimberg <sagi@grimberg.me>
> fabrics: fix endless loop in connect-all for NVME_NQN_CURR

- doc/libnvme.rst
- doc/man/struct nvme_id_ctrl.2
- src/nvme/types.h
manually recovered
nvme: add optional copy format support id ctrl field
Add the OCFS field in Identify Controller Structure, as per the
Ratified TP 4065b (Simple Copy Command).
Signed-off-by: Gollu Appalanaidu <anaidu.gollu@samsung.com>
https://github.com/linux-nvme/nvme-cli/commit/782086cc4fd590f1df171c927ebf9a2debc0a052
> recover monolithic commit 782086cc4fd590f1df171c927ebf9a2debc0a052

- libnvme/nvme.i
Fix memory leak in SWIG module.
The API PyDict_SetItemString() does not steal references
when adding objects to a dictionary. Therefore, the caller
must decrement the reference count after adding objects to
the dictionary if those objects are no longer needed.
> Fix memory leak in SWIG module

- configure
json_util_get_last_err, json_object_to_fd are supported from json-c-0.13-20171207
if json-c version is lower than 0.13, build without it
if not checking the version, make will be failed with below for lower version of json-c
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: ../src//libnvme.a(json.ol): in function `json_read_config':
/root/Desktop/repo/libnvme_upstream/src/nvme/json.c:164: undefined reference to `json_util_get_last_err'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: ../src//libnvme.a(json.ol): in function `json_update_config':
/root/Desktop/repo/libnvme_upstream/src/nvme/json.c:290: undefined reference to `json_object_to_fd' …
> Add libjson version check on configure to fix build error

- README.md
meson provides several built-in options and a few user-defined
options. 
This patch documents these different options. It also describe how 
to use the -Db_sanitize=address option and document how to 
invoke executables with the LD_PRELOAD option when this option
is used.
> Document meson build options

- src/nvme/types.h
Includes a typo correction (`enum nvmf_addr_familiy`), prefix changes (`enum nvme_trtype` -> `enum nvmf_trtype`), transition away from anonymous enums and added some more enum members according to the standard. All subtle API breaks.
Haven't found any reference to `struct nvmf_disc_log_entry.common`, leaving it without description for the time being.
> types: Fabrics doc strings updates

- src/nvme/fabrics.c
- src/nvme/fabrics.h
- src/nvme/tree.c
Two more tiny fixes. Not sure what was the original idea behind `nvmf_hostnqn_generate()` but I believe adding extra newline should be a caller responsibility.
> Misc. fabrics fixes

- src/libnvme.map
https://github.com/linux-nvme/nvme-cli/pull/1268
it cause meson build error.
repo/nvme-cli/.build/subprojects/json-c-0.15
FAILED: nvme 
cc  -o nvme nvme.p/fabrics.c.o nvme.p/nvme.c.o nvme.p/nvme-models.c.o nvme.p/nvme-print.c.o nvme.p/nvme-rpmb.c.o nvme.p/plugin.c.o nvme.p/ccan_ccan_list_list.c.o nvme.p/ccan_ccan_str_debug.c.o nvme.p/ccan_ccan_str_str.c.o nvme.p/plugins_amzn_amzn-nvme.c.o nvme.p/plugins_dera_dera-nvme.c.o nvme.p/plugins_huawei_huawei-nvme.c.o nvme.p/plugins_intel_intel-nvme.c.o nvme.p/plugins_memblaze_memblaze-nvme.c.o nvme.p/plugins_micron_micron-nvme.c.o nvme.p/plugins_netapp_netapp-nvme.c.o nvme.p/plugins_nvidia_nvidia-nvme.c.o nvme.p/plugins_scaleflux_sfx-nvme.c.o nvme.p/plugins_seagate_seagate-nvme.c.o …
> Add missing function(nvme_get_log_zns_changed_zones) to map file

- ccan/meson.build
The ccan library has support debugging, let's enable this when
building the debug version of the library.
As discussed in #128
> build: Enable ccan debug code for debug build

- src/nvme/ioctl.c
- src/nvme/ioctl.h
- src/nvme/linux.c
- src/nvme/types.h
Port of the "add get log page 2.0 spec fields" patch.
> ioctl: Add Offset Type to get_log_page()

- src/nvme/types.h
- src/nvme/util.c
Port and extent the libnvme part from the commit "Add NVMe MI
Features: Controller Metadata (0x7E) and Namespace Metadata (0x7F)."
from the nvme-cli monolithic branch.
While at it add the missing definitions and add some documentation.
This is based on Tokunori Ikegami first port attempt.
> types: Add Controller Metadata and Namespace Metadata

- src/nvme/fabrics.c
Add the definition for TLS1.3 in the transport security attribute
settings (tsas) field.
> Decode TLS1.3 transport security

- src/nvme/fabrics.c
The gcc in Centos 6.10 complains with
nvme/fabrics.c:909: error: ‘for’ loop initial declarations are only allowed in C99 mode
nvme/fabrics.c:909: note: use option -std=c99 or -std=gnu99 to compileyour code
Let's declare the index at the beginning of the basic block.
Fixes: https://github.com/linux-nvme/nvme-cli/issues/1293
> fabrics: Declare loop index at the beginning of the block

- src/nvme/util.h
The gcc in Centos 6.10 complains with
src/nvme/util.h:120: multiple definition of `nvme_feature_decode_arbitration'
'inline' alone does not guarantee that the function gets inlined. The
compiler is still free to decide, thus in this case it doesn't inline
and that's why we having multiple implementation with the same
name (in different compile units). 'static inline' forces the inline
which was the indent of this code.
Fixes: [#1293](https://github.com/linux-nvme/nvme-cli/issues/1293)
> util: Define inline function as static inline

- examples/meson.build
- libnvme/meson.build
- meson.build
- src/libnvme.map
- src/meson.build
- test/meson.build
A few more cleanups as a result from #158 and https://github.com/linux-nvme/nvme-cli/issues/1293
> Build cleanups

- meson.build
- meson_options.txt
- src/libnvme.map
- src/meson.build
- src/nvme/linux.c
- src/nvme/linux.h
- subprojects/openssl.wrap
Initially the DH-HMAC-CHAP key generation code was part of the
nvme-cli repository and depended on OpenSSL 1. Move the key generation
code into the library. While at it also add support for OpenSSL 3.
> linux: Add support to generate DH-HMAC-CHAP keys

- src/libnvme.map
- src/nvme/linux.c
- src/nvme/linux.h
Add helper to retrieve logical block size using nvme_identify_ns().
> linux: Add nvme_get_logical_block_size()

- libnvme/meson.build
Make sure the devel package is also installed not just the the Python
interpreter.
Fixes: #72
> build: Detect if Python.h header is present

- doc/conf.py
Fix for issue https://github.com/linux-nvme/libnvme/issues/165
I'm not familiar with Sphinx. By looking up the issue on Google, I found that by default Sphinx looks for a file named `contents.rst`. To specify a different name, in our case `libnvme.rst`, we must define it in `conf.py` as:
```
master_doc = 'libnvme'
```
This seems to fix the issue reported in https://github.com/linux-nvme/libnvme/issues/165.
> Fix error building the man pages

- libnvme/nvme.i
- src/nvme/fabrics.c
- src/nvme/fabrics.h
- src/nvme/private.h
- src/nvme/tree.c
Having 'host_traddr' and 'host_iface' as part of the controller
structure is technically correct, but won't work for 'connect-all'.
There we evaluate the contents of the discovery log page, and create
new controllers based on that information.
But as 'host_traddr' and 'host_iface' are Linux-only constructs, the
spec (and the discovery log page) doesn't know about them, and can't
provide us with that information.
> Move 'host_traddr' and 'host_iface' into fabrics configuration

- libnvme/nvme.i
- src/libnvme.map
- src/nvme/fabrics.c
- src/nvme/ioctl.h
- src/nvme/log.c
- src/nvme/tree.c
Add libnvme specific error codes which map to a specific error
message. The system error codes in errno are too overloaded to figure
out what is going wrong.
With this we can remove the nvme_log_message buffer. This avoids
having a global library buffer.
Fixes: #160
> log: Introduce libnvme error codes

- src/nvme/ioctl.c
- src/nvme/ioctl.h
@hreinecke suggested to rearrange the members instead adding reserved members. 
This version also adds `__attribute__((__packed__))`.
See also #170 
Fixes #169
> Fill holes in ioctl's argument structs (alternative version)

- src/libnvme.map
nvme_msg() is a macro which call __nvme_msg(). The naming scheme is
not great but until we figured it out, add it back to the list of
exported symbols.
> build: Add __nvme_msg back to exported symbols

- libnvme/nvme.i
- src/libnvme.map
- src/nvme/ioctl.h
- src/nvme/util.c
- src/nvme/util.h
Add a function nvme_errno_to_string() to provide a string describing
the error from nvme_add_ctrl().
> Implement nvme_errno_to_string()

- README.md
- src/nvme/types.h
A couple of minor updates. I've also changed the `NVMF_DISC_EFLAGS_` defines into an `enum` for consistency. Shouldn't cause any significant compatibility issues.
> Docs strings updates (#5)

- meson.build
for lower version of ssl, config will be below
#define CONFIG_OPENSSL
#undef CONFIG_OPENSSL_1
#undef CONFIG_OPENSSL_3
so function nvme_gen_dhchap_key is not defined in c file
#158 @igaw , I assume that you just allow version >=1.1.0, based on your meson changes
> meson: ssl version checking allow version >=1.1.0

- src/nvme/linux.h
The header is not self contained because nvme_get_ana_log_len() is
using the size_t type.
Fixes #182
> linux: Include missing stddef.h

- doc/libnvme.rst
- doc/man/enum nvme_id_ns_flbas.2
- src/nvme/linux.c
- src/nvme/tree.c
- src/nvme/types.h
- src/nvme/util.h
- test/test.c
flbas Bits 6:5 indicate the most significant 2 bits of
the Format Index of the supported LBA Format indicated
in this data structure that was used to format the namespace
> util: modify flbas rsvd bits to be used

- ccan/meson.build
- examples/meson.build
- internal/meson.build
- libnvme/meson.build
- meson.build
- src/meson.build
Build ccan as a static library, which gets linked to `libnvme.so`.
NOTE: since ccan depends on `config.h`, I moved the generation of `config.h` 
to the top-level `meson.build` file. It actually makes more sense to generate
`config.h` in the top-level `meson.build` file since all `subdir` projects depend 
on that file.
Refer to the discussion on pull request: https://github.com/linux-nvme/libnvme/pull/179
> Define ccan as a static library

- examples/display-columnar.c
- src/nvme/fabrics.c
- test/test.c
When compiling for 32bit architectures the compiler is complaining
about the wrong format specifier for uint64. Use the the PRIu64 format
specifier in this case which is supported from 32bit and 64bit.
Fixes: #181
> src: Use PRIu64 format specifier for uint64 types

- doc/config-schema.json
- src/nvme/fabrics.c
- src/nvme/fabrics.h
- src/nvme/json.c
Add an option 'tls' to the fabrics config to start TLS encryption
on the connection.
> fabrics: add fabrics config option 'tls'

- examples/discover-loop.c
- libnvme/nvme.i
- src/nvme/fabrics.c
- src/nvme/fabrics.h
- src/nvme/tree.c
- src/nvme/tree.h
The 'disable_sqflow' argument to nvmf_add_ctrl() is pointless, as
'struct fabrics_config' is exported and the caller can set it
directly there, without having to involve library functions at all.
And consequently we can also remove nvme_ctrl_disable_sqflow().
> fabrics: kill 'disable_sqflow' argument to nvmf_add_ctrl()

- src/nvme/ioctl.c
- src/nvme/util.c
When an error happens return -1 and set the errno.
> Fix error codes

- doc/libnvme.rst
- doc/man/nvme_scan_filter.2
- examples/discover-loop.c
- libnvme/nvme.i
- libnvme/tests/create-ctrl-obj.py
- src/libnvme.map
- src/nvme/fabrics.c
- src/nvme/json.c
- src/nvme/linux.c
- src/nvme/log.c
- src/nvme/log.h
- src/nvme/private.h
- src/nvme/tree.c
- src/nvme/tree.h
- src/nvme/util.c
- src/nvme/util.h
- test/test.c
This patchset adds an 'nvme_root_t' argument to nvme_msg(), and allows to store a different filedescriptor than 'stderr' to store in nvme_root_t. With that applications can re-route the error messages.
> Redirect error messages

- src/libnvme.map
- src/nvme/fabrics.c
- src/nvme/json.c
- src/nvme/linux.c
- src/nvme/linux.h
- src/nvme/log.h
- src/nvme/private.h
Some cleanups which can go on top of PR #202
> Rename   nvme get log page

- src/nvme/ioctl.h
Previous attempt to align the members of all *_args structure didn't
take into account that pointer types vary between 32bit and 64bit
depending the arch. The only reliable alignemnt is to sort the members
according their natural size: 64bit, pointers, 32bit, 16bit, 8bit.
```
struct nvme_identify_args {
__u32 *                    result;               /*     0     8 */
void *                     data;                 /*     8     8 */
int                        args_size;            /*    16     4 */
int                        fd;                   /*    20     4 */
__u32                      timeout;              /*    24     4 */
enum nvme_identify_cns     cns;                  /*    28     4 */
enum nvme_csi              csi; …
```
> ioctl: Sort members their natural size

- doc/index.rst
- doc/kernel-doc
- doc/libnvme.rst
- doc/regen-man.sh
- doc/regen-rst.sh
- src/nvme/fabrics.h
- src/nvme/filters.h
- src/nvme/ioctl.h
- src/nvme/linux.h
- src/nvme/log.h
- src/nvme/tree.h
- src/nvme/types.h
- src/nvme/util.h
Import the 'kernel-doc' script from the linux kernel sources and add scripts to regenerate libnvme.rst and the manual pages.
> Scripts for regenerating documentation

- src/nvme/fabrics.c
- src/nvme/json.c
- src/nvme/tree.c
- src/nvme/tree.h
Under some circumstances nvme_lookup_ctrl() might not have enough information to uniquely identify a controller. In these cases nvme_lookup_ctrl() will only ever return the first element, and any other matching element will be ignored.
This patchset adds a new parameter 'p' to nvme_lookup_ctrl() to allow the lookup to be restarted after a certain point.
> Restart controller lookup

- src/nvme/json.c
- src/nvme/private.h
- src/nvme/tree.c
- src/nvme/tree.h
Parsing the JSON configuration file might fail, so we should be signalling that to the caller.
> Return json parsing errors

- .github/workflows/meson.yml
Currently, warnings are hidden in the logs and the build is marked as
succeeded. Mark all warnings as error so that we see them show up in
the review process.
> build: Make CI build fail on warnings

- examples/telemetry-listen.c
- src/nvme/linux.c
- src/nvme/linux.h
To add support for telemetry log page data area 4, the size ptr and data area parms were added to functions: nvme_get_telemetry_log, nvme_get_ctrl_telemetry, nvme_get_host_telemetry, and nvme_get_new_host_telemetry.  
There is a corresponding pull request for the nvme cli changes that is dependent on this pull request.  
Signed-off-by: Jeff Lien <jeff.lien@wdc.com>
> [libnvme] Add Support for Telemetry Log Page Data Area 4

- .github/workflows/doc.yml
We want to catching documentation failures early. Let's add a
dedicated documentation CI build. To keep build times low just
shortcut here and do not call meson to build the complete
documentation.
> build: Add kernel-doc CI build

- src/nvme/json.c
- src/nvme/private.h
- src/nvme/tree.c
- src/nvme/tree.h
Dump the internal tree in JSON format to stdout for debugging.
> tree: add nvme_dump_tree()

- src/nvme/tree.c
We have an hard dependency on json-c, so we can rely it's always
available. Remove old ifdefs for json-c.
> tree: Remove CONFIG_JSONC ifdefs

- src/nvme/ioctl.h
> ioctl: nvme_io_args.dspec(Directive Specific) value is 16 bits

- libnvme/meson.build
- src/nvme/tree.c
valgrind reports that we are leaking memory in __nvme_free_ns() and
nvme_scan_subsystem(). Free ns->generic_name and path which makes
valgrind also happy.
> tree: Fix memleaks in __nvme_free_ns() and nvme_scan_subsystem()

- src/nvme/ioctl.h
Looks like a copy and paste error.  Corrected log page in  nvme_get_log_fw_slot to  NVME_LOG_LID_FW_SLOT instead of  NVME_LOG_LID_SMART
> Corrected FW log page used  in nvme_get_log_fw_slot

- src/nvme/ioctl.c
- src/nvme/ioctl.h
setting of cdw13 is required for Micron's latency monitoring feature. Addition of cdw13 to nvme_set_feature_args should not change the IOCTL value as nvme_passthrough_cmd has cdw13 already.
> add cdw13 for set_feature_args structure

- src/nvme/types.h
added each field description used in below structures nvme_id_independent_id_ns, nvme_id_ns_granularity_desc, nvme_id_uuid_list_entry, nvme_id_uuid_list, nvme_ctrl_list, nvme_ns_list, nvme_id_ctrl_nvm, nvme_zns_lbafe, nvme_primary_ctrl_cap
> types: Add doc description for fields used

- src/libnvme.map
- src/nvme/fabrics.c
- src/nvme/linux.c
- src/nvme/linux.h
Add uuidx parm to nvme_get_log_page and nvme_get_log_page_padded functions
Signed-off-by: Jeff Lien <jeff.lien@wdc.com>
> [libnvme] Add uuidx parm to get log page API

- src/nvme/ioctl.h
Updated the missed field description for doc section in ioctl.h file
> ioctl.h: Add description for fields used

- src/nvme/log.c
24ac082f481d ("Add 'nvme_root_t' argument to nvme_msg()") and
19b12831a9ec ("Move global logging variables into nvme_root_t") moved
the logging controller knobs into the root object. In case the pointer
is invalid we should not try to use it. Instead just bailing out just
log the line.
Fixes: #244
> log: Allow nvme_msg usage with invalid root pointer

- src/nvme/tree.c
As per section 7.4.9.3 "Transport Service Identifier" of the NVMe over
Fabrics 1.1 specification, the default IANA port number for a NVMe/TCP
discovery controller is 8009. But at the same time, it also clearly
states that NVMe/TCP I/O controllers should not use TCP port number
8009, but may instead use 4420 as the default here.
So make sure to fill these values appropriately, and pass it down.
[dwagner: backport from monolithic branch]
> fabrics: add default port number for NVMe/TCP I/O controllers

- src/nvme/types.h
updated document field section for nvme_get_features_sel, nvme_cmd_format_mset, nvme_fw_commit_ca, nvme_directive_dtype, nvme_virt_mgmt_act, nvme_virt_mgmt_rt, nvme_ns_write_protect_cfg, nvme_pevent_log_action, nvme_feat_tmpthresh_thsel, nvme_feat_plm_window_select, nvme_feat_resv_notify_flags, nvme_feat_nswpcfg_state enums
> types: Add doc section for enum fields

- src/nvme/types.h
Added missing doc for nvme_io_opcode, nvme_fctype, nvme_io_control_flags, nvme_io_dsm_flags, nvme_resv_rtype, nvme_zns_recv_action, nvme_zns_send_action, nvme_resv_cptpl, nvme_resv_rrega, nvme_resv_racqa, nvme_zns_report_options
> types: Add missing doc for ZNS, NVMe OF, NVMe command set

- src/nvme/util.c
- src/nvme/util.h
This is to resolve issue: https://github.com/linux-nvme/libnvme/issues/260
> Move ccan definitions out of public headers.

- src/nvme/util.c
updated nvme_generic_status_to_errno function with NVME_SC_PRP_INVALID_OFFSET, NVME_SC_CMB_INVALID_USE status code values in order to return EINVAL.
> util: Add status code values in geneic status to errono conversion

- src/nvme/types.h
updated the status code type value as per the NVMe specification 2.0b
> types: status code type value update as per NVMe specification

- src/nvme/fabrics.c
The kernel is taking care of swapping the system uuid bytes since
f1d8e614d74b ("drivers/firmware/dmi_scan.c: check dmi version when get
system uuid"). Hence we should not swap them again. Instead just read
/sys/class/dmi/id/product_uuid and store the bytes directly into the
system_uuid buffer.
Fixes: #263
> fabrics: Do not swap bytes for system uuid

- src/nvme/tree.c
Some FC discovery controllers return traddr strings with upper case
hexadecimal. There was is no requirement in the NVME-FC specification
that it be upper or lower case. Switch to strcasecmp for case
insentive traddr comparison.
Based on nvme-cli change 1264c6323937 ("nvme-cli: Make connect-all
matching be case insensitive")
> tree: Ignore traddr case in nvme_lookup_ctrl()

- meson.build
libnvme doesn't depend on the openssl application. Update the fallback
dependency to libssl.
Fixes: #268
> build: Depend on libssl when using the fallback dependency

- src/nvme/types.h
the error comes from fc274c57c6b3063d35dd76e36b777adc4da29e0d
using NVME_GET for masked value #148
> types: fix status code type bug (wrong masking)

- subprojects/openssl.wrap
Fixes #268
Patch taken from https://mesonbuild.com/Wrapdb-projects.html
Wrap file used https://wrapdb.mesonbuild.com/v2/openssl_1.1.1l-3/openssl.wrap
Fixed by https://github.com/mesonbuild/wrapdb/pull/322
> openssl: update to patch-3 to fix installation issue

- libnvme/meson.build
On few systems (i.e. Fedora) when running meson test,
the python library build is not invoked.
For example, on Ubuntu, this works fine.
That's why CI dodn't catch it.
So adding explicit dependency in tests.
Fixes #279
> test: adding dependency on pynvme

- .github/workflows/python-publish.yml
When using source distribution,
python package will be compiled during pip install.
Wheels make the end-to-end installation of Python packages faster:
- wheels are typically smaller in size than source distributions
- pip fetches a prebuilt wheel and avoids the intermediate step of building
So why cibuildwheel and manylinux?
See https://github.com/pypa/manylinux and https://github.com/pypa/cibuildwheel
The goal of the manylinux project is to provide a convenient way to distribute binary Python extensions as wheels on Linux
See https://github.com/pypa/cibuildwheel/blob/main/examples/github-deploy.yml
Skipping musllinux and auditwheel repair.
Skipping MacOS and Windows for now.
> CI: add python wheel build in addition to source package

- src/libnvme.map
- src/nvme/tree.c
- src/nvme/tree.h
Add a function to return the ANA state of a namespace on a given
controller.
> tree: add nvme_ctrl_get_ana_state()

- src/nvme/tree.c
nvme_free_ctrl() expects the 'trsvcid' string to be dynamically
allocated; just calling 'stringify' will cause a coredump on exit.
Fixes: https://github.com/linux-nvme/nvme-cli/issues/1433
> tree: fixup coredump during nvme discover

- doc/meson.build
- meson.build
- src/nvme/fabrics.c
- src/nvme/fabrics.h
Instead hard coding the sysconfdir allow the user to overwrite the
location of the hostnqn and hostid file. The default is "/etc" but
when configured with --prefix=DIR the files should be read from
"DIR/nvme/".
See also https://github.com/linux-nvme/nvme-cli/issues/1427
> fabrics: Allow to change sysconfdir for hostnqn and hostid file

- Makefile
see https://linux.die.net/man/8/rpmbuild
```
-ba
Build binary and source packages (after doing the %prep, %build, and %install stages).
```
> rpm: add makefile rule for rpms

- meson.build
- src/nvme/fabrics.c
Fixes: f356ab0ca74a ("fabrics: Allow to change sysconfdir for hostnqn and hostid file")
Reported-by: Hannes Reinecke <hare@suse.de>
Fixes: [ #1446](https://github.com/linux-nvme/nvme-cli/issues/1446)
> fabrics: Correctly stringify default hostnqn and hostid paths

- src/nvme/fabrics.c
Update the log level to LOG_ERR for write failures in
__nvmf_add_ctrl().
> fabrics: update log level for write failures

- src/nvme/tree.c
The subsystem instance would normally get properly initialized
in later stages of topology scanning, unless there's a host
mismatch and the instance would stand alone.
Related to #291
> tree: Fix subsystem initialization in nvme_scan_ctrl()

- src/nvme/tree.c
As noted couple of lines earlier, the subsysname string might
be NULL. In that case, defer initialization of nvme_subsystem_t
in hope that it would get initialized while scanning subsystems.
> tree: Handle NULL subsysname in nvme_scan_ctrl()

- pyproject.toml
Fixes #303
python.platlibdir and python.install_env are mutually exclusive
> CI: fixing dist packaging error

- .github/workflows/meson.yml
From https://mesonbuild.com/howtox.html#producing-a-coverage-report
Upload a report to https://codecov.io/
> ci: add code coverage

- src/nvme/fabrics.c
- src/nvme/fabrics.h
Update all callsides of nvme_chomp to use the correct max lenght of
the string to avoid out of bounds access.
While at it, nvme_chomp() is used by fabrics.c to sanitize the traddr
and trsvcid. There is no user outside of fabrics and clearly this is a
small helper function. Thus move it to fabrics and rename it to a more
comon name strchomp.
Fixes: #305
> fabrics: Avoid out of bounds string chomping

- test/test.c
test log print for passed cases and aligning
log output.
> test: print test logs for pass case

- src/nvme/fabrics.c
We need to free the old traddr and not the newly translated traddr.
```
failed to add controller, error failed to write to nvme-fabrics device
free(): double free detected in tcache 2
Program received signal SIGABRT, Aborted.
0x00007ffff6fb3cdb in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: zypper install libhugetlbfs-debuginfo-2.20-3.3.1.x86_64 libjson-c3-debuginfo-0.13-3.3.1.x86_64 libopenssl1_1-debuginfo-1.1.1d-11.38.1.x86_64 libuuid1-debuginfo-2.36.2-4.5.1.x86_64 libz1-debuginfo-1.2.11-3.24.1.x86_64
(gdb) bt
#0  0x00007ffff6fb3cdb in raise () from /lib64/libc.so.6
#1  0x00007ffff6fb5375 in abort () from /lib64/libc.so.6
#2  0x00007ffff6ff9b07 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff7001b8a in …
```
> fabrics: Free old traddr in nvmf_add_ctrl

- examples/meson.build
The 'display-tree' example program wasn't build with meson.
> meson: build display-tree example

- src/nvme/json.c
nvme_lookup_ctrl() will always create a new controller if none is
found, so checking for a NULL return value in json_parse_port() creates and endless loop.
> json: fix endless loop scanning for controllers

- src/libnvme.map
- src/nvme/fabrics.c
- src/nvme/fabrics.h
Add a function to update the fabrics configuration values of an
existing controller.
> fabrics: add 'nvmf_update_config()'

- src/nvme/tree.c
When scanning the subsystem in sysfs we cannot infer the corresponding host that easily, so rework the logic to not allocate the subsystem with the wrong host.
> Rework nvme_scan_subsystem()

- src/nvme/fabrics.c
Looks like a copy-paste issue. One of the arguments to
nvmf_register_ctrl() is "tas" (i.e. the DIM Task). This argument
should be passed to the nvmf_dim() API, but instead a fixed value
of NVMF_DIM_TAS_REGISTER was passed.
The "tas" field specifies whether to perform a "registration",
"deregistration", or a "registration update".
> fabrics: Invoke nvmf_dim() with provided tas argument.

- src/nvme/ioctl.h
The attribute packed is usually used to make sure the data structures
is compatible between different compilers in regards of padding rules.
As we have sorted the members of all argument structs according their
naturual size, there are no holes to pad. This makes the packed
attributed superflous as compilers are agree on the data layout in
this case.
The alignedof attribute is used to tell the outer alignmen of the data
structure because the aligment of a packed data structure is 1.
Anyway, both attributes doen't add any benefits to the layout and
pahole agrees on this.
This is an example the diff between the packed/aligneof version and
the plain version:
struct nvme_dim_args {
__u32 *                    result;               /*     0     8 */
void *                     data; …
> ioctl: Remove attribute packed and alignedof for args structs

- src/nvme/tree.c
Even if there was an error when reading the config file we still
should store the config file name, as it might used later on to
update/write the config file.
So parsing errors don't really matter, and we'll get notified for
I/O errors on writing anyway.
> tree: always allocate config file in nvme_read_config()

- test/meson.build
Currently, all of the meson tests are defined to just run the single
main test.
Instead, we should be defining each of the tests to use the appropriate
executable().
> test: fix meson test() executable definitions

- src/nvme/tree.c
Trying to solve the problem reported in https://github.com/linux-nvme/nvme-cli/issues/1475
> Remove default discovery port bits

- src/nvme/fabrics.c
this definition does not exist in musl libc, and has always been '%' in  
glibc\[0\] for over 20 years.  
\[0\]: https://github.com/bminor/glibc/commit/c0bc5f7b8fd62dfa566dd3adb91f3a1ee8db6aeb
> fabrics: use '%' instead of SCOPE_DELIMITER

- src/nvme/fabrics.c
9df8676d2db6 ("Add logging functionality to libnvme") introduced the
logging. The log level for writing to /dev/nvme-fabrics was set on
NOTICE because the kernel reports also status information such
EALREADY which is a soft error.
866c288a456f ("fabrics: update log level for write failures")
increased the log level without taking this into account.
Drop back to NOTICE level to avoid error message when doing
$ nvme connect-all ....
Failed to write to /dev/nvme-fabrics: Operation already in progress
See: https://github.com/linux-nvme/nvme-cli/issues/1505
> fabrics: Lower log level in __nvmf_add_ctrl

- src/nvme/fabrics.c
fabrics: Remove double connection error logging
nvmf_connect_disc_entry() is calling nvmf_add_ctrl() to do the
connecting attempt. We have in nvmf_add_ctrl() all error paths logging
enabled, so another logging in nvmf_connect_disc_entry() is not
necessary and introduces a problem such as nmve-cli users interpreting
this as hard error.
For example the kernel reports via < 0 return values state information
such as the connection is already there if the user runs 'nvme
connect-all' twice:
$ .build/nvme connect-all -t tcp --traddr=10.161.8.24  --trsvcid=4421
Failed to write to /dev/nvme-fabrics: Operation already in progress
failed to connect controller, error 1006
Let's remove this error message.
See: …
> fabrics: Remove double connection error logging

- meson-vcs-tag.sh
- meson.build
- meson_options.txt
- src/libnvme.map
- src/nvme/util.c
- src/nvme/util.h
In order to be able to figure out which binary is in use (for example
in debugging situation) it's really helpful to have the 'git describe'
ref added to the binary.
The simplest way to expose the it via good old Source Code Control
System string id. No need to come up with something complicated else
as there is no agreement on how to do this. So let's add this simple
magic string to library.
You can either query with 'what' or just
$strings .build/src/libnvme.so | grep '@(#)'
@(#)libnvme 1.0-1-g5ff5d22+
The idea how to extract the version string is shamelessly copied from
the systemd project.
> build: Add git ref to the binary

- examples/meson.build
- libnvme/meson.build
- src/meson.build
- src/nvme/private.h
- src/nvme/tree.h
- test/meson.build
- test/test.c
Per `man 3 uuid`, the correct include is `<uuid.h>`, and correspondingly the util-linux build system installs the uuid.h file to
`$(includedir)/uuid/` and uuid.pc adds `-I${includedir}/uuid` to the dependency Cflags.
Including it as `<uuid/uuid.h>` simply fails altogether. The exception is if, by coincidence, the libuuid includedir happens to be the same as one of the compiler's own internal include directories... which is pretty common if that is `/usr/include`. In this case, `<uuid/uuid.h>` fails to be found in the uuid dependency's export directories, but the compiler picks up a copy in its builtin search path.
In other cases, such as when util-linux is compiled into a custom prefix and added to the PKG_CONFIG_PATH, it either:
- fails with missing header errors, if libuuid-dev is not …
> fix broken includes for the uuid.h header

- examples/telemetry-listen.c
- src/nvme/fabrics.c
- src/nvme/tree.c
- test/zns.c
A bunch of coverity fixes; with that libnvme is now officially bug-free (tm) as far as coverity is concerned.
> Coverity fixes

- src/nvme/util.c
Without this the command "nvme get-feature /dev/nvme0 -H -f 0x0d"
segfaults because it retrieves no data but tries to use it in
nvme_show_host_mem_buffer()
> util: Add feature length for host memory buffer

- src/nvme/tree.c
A nvme config command specifying the -M & -J options would end
up in a segfault if subsysnqn is NULL, as shown below:
nvme config -M -J /etc/nvme/config.json
Segmentation fault (core dumped)
Avoid this segfault by proceeding with the subsysnqn strcmp in
nvme_lookup_subsystem() only if subsysnqn is available.
> tree: avoid segfault if subsysnqn is not available

- doc/rst/util.rst
- src/libnvme.map
- src/nvme/ioctl.c
- src/nvme/ioctl.h
- src/nvme/types.h
- src/nvme/util.c
- src/nvme/util.h
TP 4068 - Protection Information Enchancement
TP 4084 - Time-to-Ready Enhancements
> Changes to support TP 4068 and TP 4084 

- src/libnvme.map
- src/nvme/fabrics.c
- src/nvme/private.h
- src/nvme/tree.c
fabrics: Consider config from file when adding new controller
nvme_read_config() function is attaching the configuration
to tree. But when we create a new controller via nvme_create_ctrl()
and then call nvmf_add_ctrl() we ignore this previously read
in configuration.
Hence lookup if there exist a controller/config and merge into
the fabrics config.
Note, the order of the merge is important. For example we want
the config from the command line to have higher priority
than the one from the config file.
Fixes: https://github.com/linux-nvme/nvme-cli/issues/1520
> Consider file config when adding controller

- src/nvme/ioctl.h
This patch adds definition of structure nvme_uring_cmd and two new opcodes
NVME_URING_CMD_IO / NVME_URING_CMD_IO_VEC. This new structure
definition and opcodes are required for using uring-nvme-passthrough
feature. This feature has been picked for 5.19 kernel.
https://git.kernel.org/pub/scm/linux/kernel/git/axboe/linux-block.git/log/?h=for-next
Link to the patches
https://git.kernel.org/pub/scm/linux/kernel/git/axboe/linux-block.git/commit/?h=for-next&id=456cba386e94f22fa1b1426303fdcac9e66b1417
https://git.kernel.org/pub/scm/linux/kernel/git/axboe/linux-block.git/commit/?h=for-next&id=f569add47119fa910ed7711b26b8d38e21f7ea77
> ioctl: nvme_uring_cmd add structure and opcodes

- src/libnvme.map
For some reason it has been missing from the map file.
> libnvme: export 'nvme_scan_ctrls'

- src/nvme/fabrics.c
- src/nvme/util.c
- src/nvme/util.h
The kernel returns status information via error codes. Currently we
map all error codes to ENVME_CONNECT_WRITE if the operation
fails. Some of those error codes should be treated differently, such
as EALREADY which means the connection attempt failed because the
connection is already established.
Many of the error codes are overloaded so we have to guess if they are
actually from the nvme subsystem and not from the write
command. Though in practice it's almost certainty the nvme
subsystem. Still it's a guessing game due the very limited API
between userland and kernel.
See: #https://github.com/linux-nvme/nvme-cli/issues/1505
> fabrics: Introduce connection connect error mapping

- meson.build
- test/meson.build
Currently, the meson project configuration specifies both 'c' and 'ccp'
languages. We use the latter to build a single test binary.
This change makes the cpp language optional, so we can compile the rest
of libnvme without a C++ environment.
> meson: only build test/cpp if a c++ compiler is available

- examples/display-tree.c
- examples/telemetry-listen.c
We have a few warnings from mismatched printf format specifiers on
32-bit builds. Use PRIu64 for uint64_t, and %z for size_t.
> examples: Fix printf format warnings on 32-bit

- examples/meson.build
- examples/mi-mctp.c
- meson.build
- src/libnvme-mi.h
- src/libnvme-mi.map
- src/meson.build
- src/nvme/mi-mctp.c
- src/nvme/mi.c
- src/nvme/mi.h
- src/nvme/private.h
- test/meson.build
- test/mi.c
This series implements the NVMe Management Interface (NVMe-MI), allowing management of NVMe devices through an out-of-band MCTP channel, using the new `AF_MCTP` sockets support in Linux.
These introduce a separate shared library - `libnvme-mi.so`, as the library's consumers would typically be different from those using `libnvme.so`. I'm open to feedback on the best structure for integrating the MI layer though.
This series is on top of the `fixes` PR (#75).
With these changes, and an `AF_MCTP`-enabled kernel, I can interact with NVMe hardware over the out-of-band SMBus channel:
```
NVMe MI subsys info:
num ports: 2
major ver: 1
minor ver: 0
NVMe MI port info:
port 0
type PCIe[1]
MCTP MTU: 0
MEB size: 0
PCIe max payload: 0x4000
PCIe link speeds: 0x00
PCIe current speed: 0x00
PCIe max link …
```
> Initial NVMe-MI protocol support

- src/nvme/ioctl.h
Both function should always be inlined.
Fixes: #377
> ioctl: Add inline to nvme_identify_cns_nsid and nvme_get_log_ana

- README.md
- doc/index.rst.in
- doc/installation.rst.in
The min kernel version is v4.15 kernel because libnvme depends on the
/sys/class/nvme-subsystem interface.
Signed-off-by: Daniel Wagner [dwagner@suse.de](mailto:dwagner@suse.de)
Fixes https://github.com/linux-nvme/nvme-cli/issues/1516
> README: add note about min kernel version

- .github/workflows/meson.yml
v4 of the setup-python helper wants to know the python version number.
> ci: add python version to setup-python environment

- src/nvme/tree.c
The list of namespaces needs to be considered static, and should
only be changed on a full rescan. So simplify the function to just
return the corresponding namespace entry from the topology tree.
Fixes: #364
> tree: simplifiy nvme_subsystem_lookup_namespace()

- examples/mi-mctp.c
- src/libnvme-mi.map
- src/nvme/api-types.h
- src/nvme/ioctl.h
- src/nvme/mi.c
- src/nvme/mi.h
This changeset unifies the first set of MI Admin commands to use the `_args`-struct-style API, and updates the example code in `mi-mctp` to suit, and clarify the usage of the `identify_partial` function.
This is dependent on https://github.com/linux-nvme/libnvme/pull/384 to expose those `_args` types.
As always, let me know if you have any queries/comments!
> MI: Update MI Admin API to suit core

- src/meson.build
Signed-off-by: Jeff Lien <jeff.lien@wdc.com>
This will fix compile errors seen with the latest nvme-cli code needing the api-types.h include file.
> build: Add api-types.h to install headers

- meson.build
We're currently basing the host endian tests on the build_machine; we
should be using host_machine instead.
> meson: use host target for defining endianness

- src/nvme/mi.c
- src/nvme/mi.h
- test/mi.c
This series adds a couple of tests for the initial Admin command infrastructure, and a fix for how we serialise some of the lesser-used identify fields, particularly on big-endian platforms. We also have a cleanup to unify the admin function naming scheme.
As always, please let me know if you have any comments/queries.
> MI: tests and fixes

- examples/mi-mctp.c
- src/libnvme-mi.map
- src/nvme/mi.c
- src/nvme/mi.h
This series adds a few new admin commands to the set supported by MI:
- Get Log Page
- Security Send
- Security Receive
As usual, these share the `_args` structs used for the core libnvme interface.
We also add a "raw" interface, as a basic interface for performing arbitrary commands.
For each of the added commands, extend the `mi-mctp` example application to show usage. In the case of the security commands, we use Security Protocol 0 to query the other protocols supported by the controller.
> MI: add further admin commands

- src/nvme/api-types.h
- src/nvme/ioctl.h
- src/nvme/tree.h
- src/nvme/types.h
- src/nvme/util.h
Add missing documentation bits to all header files except types.h.
This a very rudimentary and surely needs a to be refined later. But
let's first try to get kernel-doc to report 0 warning/errors so we can
actually detect offenders added by new code.
> doc: Add kernel-doc to header files

- test/meson.build
- test/mi.c
When generating th coverage report, lcov chokes on the '../src/nvme'
paths prefix:
geninfo: WARNING: GCOV did not produce any data for /home/wagi/work/libnvme-upstream/obj/src/test-mi.p/.._test_mi.c.gcda
We could restructure the project layout, e.g. by moving the test/mi.c
file to the src/nvme direcotry. But that looks ugly and as it turns
out we only really need one function copied over
nvme_mi_crc32_update() to resolve the dependency. The other function
is nvme_mi_init_ep() which we can easily open code.
Obviously, it would be better to fix the path issue for lcov but for
the time being let's go with this.
Fixes: #393
> test: Remove code dependency for mi test

- src/nvme/fabrics.c
When calling merge_config() in nvmf_add_ctrl() the controller
authentication key can't be updated reliably as it may already
been set. So update the controller with the correct key
manually.
Suggested-by: Sagi Grimberg <sagi@grimberg.me>
> fabrics: Update controller authentication in nvmf_add_ctrl()

- .github/workflows/doc.yml
- doc/api.rst
- doc/api.rst.in
- doc/index.rst
- doc/index.rst.in
- doc/meson.build
- doc/mi.rst.in
- src/nvme/mi.c
- src/nvme/mi.h
This change adds kernel-doc documentation for the new definitions in `mi.h`, and a file-level header for general API information.
We also fix a misnamed argument found while writing the docs, added as a small prerequisite patch.
Let me know if I've missed any conventions from the core libnvme docs.
> MI: Add kernel-doc documentation for MI API

- doc/mi.rst
It looks like the generated doc output on readthedocs.io requires the
processed .rst output to be present in the repo, so check it in.
> doc: check-in processed mi.rst

- src/libnvme-mi.map
- test/mi.c
Ideally, we would be using the actual implementation of
nvme_mi_init_ep() for our tests, rather than open-coding it in the test
init.
This change exports the nvme_mi_init_ep from libnvme-mi.so, but it
remains excluded from the headers, as it's only intended for use in the
transport API. This means we can call it from the tests, but keep is
somewhat-internal.
We put this into a specific _TEST section of the version script, to keep
separate from the public symbols.
This prevents us from diverging the endpoint init process in our
testcases.
> MI: reinstate nvme_mi_init_ep for endpoint initialisation in test

- src/libnvme-mi.map
- src/meson.build
- test/meson.build
We previously exposed a couple of internal functions for libnvme-mi.so
in ce4a044720. However, Daniel Wagner has suggest instead using a
separate shared library with all symbols visible, just for the unit
test.
This change reverts the symbol visibility changes for the installed
libnvme-mi.so, and defines a separate, non-installed library for the MI
unit tests. This is the same as libnvme-mi.so, but has no linker script
or versioning information.
This means we're not exposing the init_ep and crc32 functions in the
actual .so, but can still allow unit tests to access non-public symbols.
The coverage reports can handle the separate library just fine, as the
coverage data is correlated on the underlying source files.
> test: define separate library for MI unit tests

- doc/mi.rst
- doc/mi.rst.in
- examples/mi-mctp.c
- meson.build
- src/libnvme-mi.map
- src/meson.build
- src/nvme/mi-mctp.c
- src/nvme/mi.c
- src/nvme/mi.h
- src/nvme/private.h
- src/nvme/tree.c
- test/mi.c
The MCTP userspace infrastructure provides the set of discovered endpoints over dbus. This series adds a facility to query that list for endpoints that report support for the NVMe-MI protocol, and add them to the `nvme_root_t`.
With that information, we can add iterators to traverse the results of the scan.
This dbus mechanism is conditional on the low-level sdbus interface library, provided by libsystemd, and is enabled/disabled at `meson setup`.
As always, comments, queries, etc. are most welcome.
> MI: Add endpoint iterators, and allow scanning from MCTP endpoints on dbus

- src/meson.build
Now that we have a decent amount of the libnvme-mi definitions fairly
stable, add the top-level libnvme-mi.h header to the installed header
set.
> MI: install top-level libnvme-mi.h header

- src/nvme/types.h
The NVMe-MI spec defines the Composite Controller Status definitions
using the abbreviation CCS. However, the libnvme code (since initial
commit) has used CSS, not CCS (except for CCS_RDY...).
This change fixes the definitions to use the _CCS_ names, and adds a set
of #defines to allow the old names to be used, including for the enum
itself.
> types: fix typo on nvme_mi_ccs definitions in public API

- examples/mi-mctp.c
- src/libnvme-mi.map
- src/nvme/mi.c
- src/nvme/mi.h
- test/mi.c
This change adds an API to send MI Get / Set Configuration commands to
an endpoint, allowing control of endpoint SMBus frequenct, MCTP MTU and
clearing the subsystem health status bits.
We do this with a new couple of functions:
int nvme_mi_mi_config_get(nvme_mi_ep_t ep, __u32 dw0, __u32 dw1,
__u32 *nmresp)
int nvme_mi_mi_config_set(nvme_mi_ep_t ep, __u32 dw0, __u32 dw1)
The dw0, dw1 and nmresp formats depend on the type of configuration
accessed, which can be a little opaque. Se we add a bunch of helpers
too, to get/set the three configuration params:
nvme_mi_mi_config_get_smbus_freq(...);
nvme_mi_mi_config_set_smbus_freq(...);
nvme_mi_mi_config_get_mctp_mtu(...);
nvme_mi_mi_config_set_mctp_mtu(...);
nvme_mi_mi_config_set_health_status_change(...);
[there's no getter for the latter, as …
> mi: Add MI configuration commands

- src/nvme/mi-mctp.c
- src/nvme/mi.c
- src/nvme/mi.h
This series implements a unification of the return values across the MI code, so that we have consistent semantics between libnvme and libnvme-mi.
From the final patch:
> This gives us the following semantics:
>
> - zero on success
>
> - -1 for errors in the MI communication with an endpoint, with errno
>   set accordingly
>
> - positive values where the MI communication succeeded, but we received
>   an error response from the endpoint. The return value will be that
>   from the MI response status field, and should correspond to one of
>   the nvme_mi_resp_status values.
Patch 1 extends the defined MI status values, so we're complete with what's in the current spec, and patch 2 implements a small fix to the error handling when we have duplicate endpoints during a scan.
As always, …
> MI:  return value + errno unification

- src/nvme/api-types.h
- src/nvme/fabrics.h
- src/nvme/ioctl.h
- src/nvme/linux.h
- src/nvme/mi.h
- src/nvme/tree.h
- src/nvme/types.h
- src/nvme/util.h
The first patch fixes the obvious typos. Though while I was at it, I thought it might be worth to fix with some tooling the whitespace damages in the header files (my OCD wanted this). Personally I think the result is excellent but I understand if people hate this type of change.
Fixes #96
> Fixing typos and whitespace damage in header files

- libnvme/nvme.i
Python bindings are extended to report the EFLAGS when a discovery
command is issued. This was previously missing.
> python: add eflags to discovery log page

- libnvme/__init__.py
- libnvme/meson.build
It is customary for Python packages to provide a __version__ attribute
> python: add __version__ to libnvme python package

- doc/meson.build
In e33cc17 we removed an inner loop on the result of files(), but didn't
update the local variable to suit.
This change uses the correct iterator variable for the configure_file()
invocation.
Reported-by: Daniel Wagner <dwagner@suse.de>
> doc: Use correct variable in configure_file input

- examples/mi-mctp.c
- src/libnvme-mi.map
- src/nvme/mi.c
- src/nvme/mi.h
In the MI interface, we currently have:
```c
nvme_mi_admin_get_log_page(...)
```
However, the ioctl-backed API equivalent doesn't use the `_page`:
```c
nvme_get_log(...)
```
This change makes the MI version consistent, where we have the
equivalent names, just with the `mi_<type>` prefix:
```c
nvme_mi_admin_get_log(...)
```
> mi: unify MI Get Log Page function with ioctl API

- .gitignore
- Makefile
- libnvme.spec.in
- Build will be happen in Makefile using meson
- Using meson build directory instead of Source(tar.gz)
- meson is needed higher version then what rpm repo offering (use pip install)
- Enable building static library (default: shared)
> rpmbuild: Enable 'make rpm' to build rpm pkgs #408

- meson.build
LibreSSL ships with the same API but has a different version number
scheme. That is LibreSSL 3.x is not providing the OpenSSL 3.x
APIs. Hence we need to test if the OpenSSL 3 APIs are available if
LibreSSL is present.
Reported-by: Ismael Luceno <ismael@linux.com>
Fixes: #434
> build: Add support to build against LibreSSL

- meson.build
-nostdinc is only necessary when the LibreSSL is not the default SSL
library on the system and OpenSSL header files are present in the
default include paths.
Though if LibreSSL found in standard paths 'pkg-config --cflags' will
include the standard include paths and hence the header files are not
found.
So -nostdinc is only useful for mixed installations which is very
unlikely a very common setup. So let's just drop the -nostdinc and if
the need is to support such setups, we can still try to figure out
how to support this.
See also discussions in #439
> build: Drop -nostdinc for LibreSSL header checks

- src/nvme/json.c
Trivial fix to sanitize the dump-config output by appending a
new line at the end.
> fabrics: sanitize dump-config output

- src/nvme/ioctl.h
The nvme_get_nsid_log() helper has a rae (Retain Asynchronous Events)
parameter, but we currently ignore this when constructing the Get Log
Page command arguments.
This is a behavior change and not an API change. But the good thing is
only for newly build binaries because all helpers are static inline
fuctions.
Reported-by: Reported-by: Jeremy Kerr <jk@codeconstruct.com.au>
Fixes: #437 
BTW, I've decided against updating `test/test.c`, as I am not sure if this
was intended setting or just set without a lot of thinking.
> ioctl: Honor rae in nvme_get_nsid_log

- src/nvme/fabrics.c
A small issue spotted by reading the code.
> fabrics: Fix build_options() return values

- doc/config-schema.json
- src/nvme/json.c
- src/nvme/tree.c
The config schema declared a 'dhchap_key' and a 'dhchap_ctrl_key'
value for the port structure, but the json parser implemented a
'dhchap_key' entry for the port (holding the controller key), and
a 'dhchap_key' entry for the host (holding the host key).
Fixup the config schema to declared the correct entries and the
json parser to check for 'dhchap_ctrl_key' instead of 'dhchap_key'.
Fixes: Issue #426
> json: fixup dhchap_ctrl_key definitions

- .github/workflows/python-publish.yml
- meson.build
- release.sh
This changes slightly how releases are done. It's possible now to have the `-rc[0-9]+` suffix added to the project version. 
Fixes #429
> Add support for uploading release candidates to PyPI

- src/nvme/util.c
The bionic libc implementation doesn't implement the complete
POSIX API. Apperantly we just need this define to be able
to compile for Android OS. Thus, keep it as simple as possible
and just define it here.
Fixes: #452
> util: Add LINE_MAX define

- src/libnvme-mi.map
- src/nvme/mi.c
- src/nvme/mi.h
- test/mi.c
This series adds MI implementations for more Admin commands:
* Get Features
* Set Features
* Namespace Management
* Namespace Attach
* Format NVM
* Sanitize NVM
plus a few inline helpers for these and the existing Get Log Page and Identify commands (which `nvme-cli` needs to support the above)
As always, comments/queries/etc most welcome.
> MI: expand admin command implementation

- examples/meson.build
- examples/mi-conf.c
With the Read MI Data Structure and MI Configuration Set functions
available, we can query a device for its maximum MTU, and update the
current MTU to suit.
This also requires telling the local MCTP stack about the new MTU too,
by sending a d-bus message to `mctpd`.
This change adds a little example for this functionality, where we
perform the MI query and configuration, and implements the d-bus
communication for the local stack control.
> example/mi-conf: Add an example for MI transport configuration

- src/nvme/mi-mctp.c
- test/mi-mctp.c
Devices may implement their MPR response as an actual Admin response
message, rather than the simple MI-only message described in 4.1.2.3 of
NVMe-MI v1.2b.
Allow this, but with some fairly stringent header checks. Add a test for
this behaviour too.
> mi: Allow Admin-message sized More Processing Required responses

- doc/config-schema.json.in
- libnvme/nvme.i
- src/libnvme.map
- src/nvme/fabrics.c
- src/nvme/json.c
- src/nvme/private.h
- src/nvme/tree.c
- src/nvme/tree.h
The json config schema already defines a DHCHAP host key on the controller level, so add the infrastructure for parsing and setting it. And while we're at it fixup the json config schema to define the DHCHAP key on the host level.
Fixes: #426
> Allow to get and set DHCHAP host key on controller level

- src/nvme/tree.c
Seeing multiple segfaults in nvme_configure_ctrl() when the
respective controller attributes (including auth keys) are
unavailable. For e.g. attempting a nvme connect with bidirectional
auth hits the following segfault:
nvme connect -t tcp -w 192.168.1.16 -a 192.168.1.116 -n
nqn.1992-08.com.netapp:sn.48391d66c0a611ecaaa5d039ea165514:subsystem.subsys_CLIENT116
-S DHHC-1:01:k+fO3MFyRpOwrPTUQh0ewZI58uf8bwn5H9RnHle4Q8U37aJe:
-C DHHC-1:03:KEVxLQLJxugDXw/tWm9VmZuas38ath9HWzpq+cDprHafC4yuVg+McEQgEltOJAIIziNfWWKaw8mpPrnSQqqQuHKE5zQ=:
Segmentation fault (core dumped)
In another instance, a segfault is seen if no keys are specified
in the nvme connect:
nvme connect -t tcp -w 192.168.1.16 -a 192.168.1.116
-n nqn.1992-08.com.netapp:sn.48391d66c0a611ecaaa5d039ea165514:subsystem.subsys_CLIENT116 …
> nvme-tree: avoid segfault if auth keys are unavailable

- doc/list-pre-compiled.sh
- doc/meson.build
The install_subdir('man', ...) command installs the man pages under
$mandir/man/ instead of $mandir. Use and external script to get the
list of man pages to avoid having to list all the man pages
explicitly.
> doc: Install pre-compiled man pages to the correct path

- doc/config-schema.json
One can set the dhchap_key in the host section as well of the config JSON file. So update the JSON schema to reflect the same.
> json-schema: add dhchap_key details to host section

- examples/mi-mctp.c
gcc-12 with `-Wuninitialized-var` reports a warning for `mi-mctp`:
examples/mi-mctp.c: In function ‘do_action_endpoint’:
examples/mi-mctp.c:665:16: warning: ‘rc’ may be used uninitialized [-Wmaybe-uninitialized]
665 |         return rc;
|                ^~
examples/mi-mctp.c:637:13: note: ‘rc’ was declared here
637 |         int rc;
|             ^~
We shouldn't be able to hit this path, but explicitly set rc to an error if we miss an enum case.
Fixes: https://github.com/linux-nvme/libnvme/issues/467
> examples/mi-mctp: fix warning for possibly uninitialised variable

- src/nvme/types.h
Submitting as a separate commit (and pull request) per discussion: https://github.com/linux-nvme/libnvme/pull/474#discussion_r977523864
This is to prepare for additional TP8010 changes related to the Get Discovery Log Page command. More precisely, the ability to set the LSP field (Log page SPecific) of the Get Discovery Log Page command.
> fabrics: Add new TP8010 definitions

- src/nvme/mi.h
- test/mi.c
This change adds a helper for the Identify command, retrieving the secondary controller list. We add a simple test too.
> mi: Add Identify function for secondary controller list

- .github/cross/ubuntu-armhf.txt
- .github/cross/ubuntu-ppc64le.txt
- .github/workflows/meson.yml
This RFC change adds a github workflow for a cross-compile of libnvme on armhf & powerpc64le We use a similar setup to the build-distro job, but install a suitable cross compiler and provide a cross config to meson.
We currently setup with -Dpython=false, as the setup-python@v4 seems to assume a native python build. We may be able to remove this later.
The suitability of this will depend on the resources available for actions; doing some test runs on a private repo shows an execution time of about 1 min 15 sec per cross build - a little less than the build-static job.
> github workflows: Add armhf & powerpc64le cross builds

- src/libnvme-mi.map
There have been a few functions added after the v1.1 release that ended up in the 1_1 section of the symbol map. This change moves them to a new 1_2 section instead.
> mi: Move post-1.1 symbols to 1_2 section of libnvme-mi.map

- src/libnvme-mi.map
- src/nvme/mi.c
- src/nvme/mi.h
- test/mi.c
This change adds MI implementations for the Firmware Download and Firmware Commit admin commands, as well as a couple of tests.
As usual, these are designed to match the ioctl API.
> mi: Add firmware download and commit commands

- src/libnvme.map
- src/nvme/fabrics.c
- src/nvme/fabrics.h
TP8010 introduces new values for the Log page Specific field (LSP) in the "Get Discovery Log Page" command. Previously, the LSP field was unused and set to 0. 
This pull request adds function `nvmf_get_discovery_wargs()`. This function is similar to `nvmf_get_discovery_log()`, but takes an extensible "`args`" parameter. `nvmf_get_discovery_wargs()` allows setting more options (including the LSP)  than `nvmf_get_discovery_log()`. 
> fabrics: Add nvmf_get_discovery_wargs()

- examples/discover-loop.py
- libnvme/README.md
- libnvme/nvme.i
Refactor code to use `nvmf_get_discovery_wargs()` which allows setting the LSP field. Needed for TP8010 support (i.e. setting PLEO bit).
Also, added `supported_log_pages()` which is used to determine whether the PLEO bit is supported (PLEOS).
Finally, updated the Python example code that was a bit outdated.
> python: Use nvmf_get_discovery_wargs()

- src/nvme/mi.h
The admin cmd of libnvme-mi returns negitive number(-1) with errno. Otherwise it returns nvme-mi status byte (byte 4). And status = 0 means `Success`.
It is the same behavior as the none-mi version. Align the description of libnvme-mi to libnvme.
Signed-off-by: Hao Jiang <jianghao@google.com>
> Add more details for return code of MI admin cmds

- src/nvme/mi-mctp.c
If the call to ops.socket() fails, the mctp pointer will be leaked.
> libnvme: fix a memory leak in nvme_mi_open_mctp()

- src/nvme/json.c
While working on the a related topic, I run into several crashes due to wrong formatted JSON. 
The crashes happened inside the json-c library:
```
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff7dbe893 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff7d6b846 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7d5481c in __GI_abort () at abort.c:79
#4  0x00007ffff7d5472b in __assert_fail_base (fmt=0x7ffff7edaa80 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7ffff7f721f0 "json_object_get_type(jso) == json_type_array", 
file=0x7ffff7f72048 "/home/abuild/rpmbuild/BUILD/json-c-json-c-0.16-20220414/json_objec …
```
> Enforce correct JSON config format

- src/nvme/mi.c
- test/mi.c
In our get_log_page helper, we're incorrectly checking the requested chunk offset against the chunk len, rather than the overall length - this means we can't query anything but the first chunk.
This change fixes this to check against the overall length instead, and adds an additional check to ensure we're not requesting more than the full data size.
We also add a testcase for the chunking code.
Reported-by: Hao Jiang <jianghao@google.com>
> mi: fix get_log_page chunked offset check

- src/libnvme.map
- src/nvme/fabrics.c
- src/nvme/util.c
- src/nvme/util.h
Since feature identifier 0Dh: host memory buffer length is affected by the direction as mentioned by the issue #1681.
Signed-off-by: Tokunori Ikegami <ikegami.t@gmail.com>
> libnvme: Add direction parameter to get feature length

- Makefile
This PR adds ``make uninstall``.
Example output is provided below, showing how ``make uninstall`` behaves after ``make install``.
Equivalent PR provided for **nvme-cli**: https://github.com/linux-nvme/nvme-cli/pull/1704
**Install**
```
safl@debtop:~/git/libnvme$ make && sudo make install
meson .build
The Meson build system
Version: 0.60.0
Source dir: /home/safl/git/libnvme
Build dir: /home/safl/git/libnvme/.build
Build type: native build
Project name: libnvme
Project version: 1.1
C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
C linker for the host machine: cc ld.bfd 2.35.2
Host machine cpu family: x86_64
Host machine cpu: x86_64
C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")
C++ linker for the host …
```
> Makefile: add 'make uninstall'

- src/libnvme-mi.map
- src/nvme/mi.c
- src/nvme/mi.h
- src/nvme/types.h
- test/mi-mctp.c
As a fix for https://github.com/linux-nvme/libnvme/issues/456, this PR adds a new encoding for the status values of the `nvme_mi_*` and `nvme_*` API, with the latter being completely unchanged.
To do this, we use the top set of bits in the `int` return value as an encoding of the "type" of status value; possible types are currently NVMe (as existing, from CDW3), and MI (from the status field of the MI header). The most-significant bit is already used for the sign bit (where negative values already represent internal errors, rather than NVMe status), so we use the next three significant bits to represent a type, and allow for future expansion of the possible types in future
For NVMe status, we only need the lower 15 bits of the int; for MI, we only need the lower 8.
So, an NVMe status …
> Add encoding for MI/NVMe status values

- examples/mi-conf.c
The sd_bus methods may return EINVAL if err is not initialised to NULL.
> examples/mi-conf: Initialise sd_bus_error

- examples/mi-conf.c
The NVMe specs don't include the MCTP header when referring to the MCTP MTUs; we need to do so when setting the Linux route MTU.
This change uses the header-included value when setting the route MTU via mctpd over dbus.
> examples/mi-conf: account for MCTP header in route MTU

- src/libnvme.map
Add nvme_ctrl_is_persistent() to the global list for use in nvme-cli.
> libnvme.map: add nvme_ctrl_is_persistent()

- meson.build
- src/libnvme.map
- src/meson.build
- src/nvme/fabrics.c
- src/nvme/private.h
- src/nvme/tree.c
- src/nvme/tree.h
- src/nvme/util.c
- src/nvme/util.h
- test/meson.build
- test/test.c
- test/uuid.c
Provide our own UUID type as there is no point to have a dependency on libuuid just for a couple function we use.
> util: Add simple UUID type

- src/nvme/ioctl.h
- src/nvme/mi.h
These function do not sett the passed in offset. Fix this.
Fixes #472
>  Set log page offset for nvme_{mi}_get_log_telemetry_host

- meson.build
python3.extension_module() is depending on gnu_symbol_visibility. So arguably, this has been from day 0.
Version 0.47 was released on Jul 02, 2018 and 0.48 on Sep 22,
2018. Even Debian oldstable ships 0.49.
Fixes: #496
> build: Update min version of meson to 0.48

- src/nvme/fabrics.c
We have to use strdup here, because the merged config will be freeing these pointers eventually. Without it, we are going to double free it.
Fixes: https://github.com/linux-nvme/nvme-cli/issues/1707
> fabris: Use doublicate string when merging configs

- src/nvme/types.h
- src/nvme/util.h
As this is part of the spec, let's move this to the types.h header file.
> types: Move enum nvme_data_tfr to types

- src/nvme/mi.c
ctrl_id of 0 should be still considered as valid. Remove the condition check correspondingly.
Signed-off-by: Hao Jiang <jianghao@google.com>
> mi: Allow zero as a controller ID in nvme_mi_scan_ep

- doc/mi.rst
- doc/mi.rst.in
- src/libnvme-mi.map
- src/nvme/mi-mctp.c
- src/nvme/mi.c
- src/nvme/mi.h
- src/nvme/private.h
We have found that some devices need small workarounds ("quirks") for proper MI-channel functionality.
This series introduces a little infrastructure for these changes, triggered by a probe of the Controller's Identify data. Based on that data, we have a new bitmask (`quirks`) in the endpoint structure:
```diff
@@ -195,6 +196,7 @@ struct nvme_mi_ep {
bool controllers_scanned;
unsigned int timeout;
unsigned int mprt_max;
+       unsigned long quirks;
};
```
which can be queried via a helper:
```c
static bool nvme_mi_ep_has_quirk(nvme_mi_ep_t ep, unsigned long quirk)
```
Using this, we introduce our first quirk: a delay between commands, required by a specific NVMe device:
```c
/* Set a minimum time between receiving a response from one command and
* sending the next request. Some devices …
```
> MI quirk implementation

- libnvme/nvme.i
Release Python's GIL (global interpreter lock) when invoking blocking functions from multithreaded Python applications. This is to prevent long running threads to block all other threads.
Some I/O operations can run for a long time (seconds). For example, when connecting to a remote controller over fabrics, the timeout for a failure to connect is 3 seconds. If we do not release the GIL before calling a blocking function, all threads of a Python application could be blocked for several seconds. 
Ref: https://docs.python.org/3/c-api/init.html?highlight=gil#releasing-the-gil-from-extension-code
> python: Release GIL on blocking calls

- src/nvme/mi.c
nvme_mi_admin_admin_passthru forgets to check the rc after nvme_mi_admin_parse_status.
Signed-off-by: Jinliang Wang <jinliangw@google.com>
> mi: fix rc checking

- src/nvme/mi.c
- test/mi.c
We have a couple of endian issues in the mi code: one where we're not converting cdw0 for MI commands, and one where we're using the wrong byte length for an existing conversion. There is also an error in the test suite, where we should be converting the `nsze` field of a `nvme_id_ns`.
This change fixes those, so that the test suite passes on a BE platform (ppc64 in my case).
Fixes: https://github.com/linux-nvme/libnvme/issues/524
> mi: endian fixes

- meson.build
The Meson buildspec uses features introduced in Meson 0.50.0, but only specifies 0.48.0. Eliminates a Meson warning.
Signed-off-by: nick black <dankamongmen@gmail.com>
> build: require meson 0.50.0+

- meson.build
We should always set the CONFIG_LIBSYSTEMD independend if the library has been found.
Use also the more clear declare_depdency() to express library not found.
While at it also use more streamlined names for the checks.
> build: Always set CONFIG_LIBSYSTEMD variable

- .github/cross/ubuntu-armhf.txt
- .github/cross/ubuntu-ppc64le.txt
- .github/workflows/meson.yml
Use qemu-user-static wrapper to run cross compiled tests.
> build: Run cross build test under qemu

- src/nvme/fabrics.c
Fixes: https://github.com/linux-nvme/libnvme/issues/537
> fabrics: Fix bad UUID size introduced in recent UUID changes

- src/nvme/mi-mctp.c
- src/nvme/mi.c
We need to do more than free() on endpoint close, so call nvme_mi_close on endpoint creation failure.
> mi: call nvme_mi_close on endpoint error path

- examples/meson.build
- examples/mi-conf.c
- meson.build
- src/meson.build
- src/nvme/mi-mctp.c
libsystemd is not generally available as a static library, and we would like to produce a static nvme-cli. This change switches to libdbus instead.
This requires slightly more boilerplate code for the dbus marshalling/unmarshalling as part of the MCTP endpoint scan, but means we have a simpler upstream lib dependency.
Fixes: https://github.com/linux-nvme/nvme-cli/issues/1734
> MI: switch from libsdbus to libdbus

- src/nvme/fabrics.c
Valgrind complaining about accessing uninitialized memory:
==159962== Conditional jump or move depends on uninitialised value(s)
==159962==    at 0x484BCF6: rawmemchr (vg_replace_strmem.c:1564)
==159962==    by 0x4F52B15: _IO_str_init_static_internal (strops.c:41)
==159962==    by 0x4F1DAB1: UnknownInlinedFun (strfile.h:95)
==159962==    by 0x4F1DAB1: __isoc99_sscanf (isoc99_sscanf.c:28)
==159962==    by 0x7B77C97: uuid_from_dmi_entries (fabrics.c:969)
==159962==    by 0x7B84192: UnknownInlinedFun (fabrics.c:1059)
==159962==    by 0x7B84192: nvmf_hostnqn_generate (fabrics.c:1070)
> fabrics: Fix uuid_from_dmi_entries() read buffer initialization

- src/nvme/tree.c
```
==306445== 96 bytes in 16 blocks are definitely lost in loss record 3,171 of 3,553
==306445==    at 0x484386F: malloc (vg_replace_malloc.c:393)
==306445==    by 0x4FA2F6D: strdup (strdup.c:42)
==306445==    by 0x7B9C477: nvme_ns_set_generic_name (tree.c:1802)
==306445==    by 0x7B9C51B: nvme_ns_open (tree.c:1820)
==306445==    by 0x7B9C606: __nvme_scan_namespace (tree.c:1853)
==306445==    by 0x7B9CA0C: nvme_subsystem_scan_namespace (tree.c:1931)
==306445==    by 0x7B98C81: nvme_subsystem_scan_namespaces (tree.c:496)
==306445==    by 0x7B991BC: nvme_scan_subsystem (tree.c:597)
==306445==    by 0x7B97DA1: nvme_scan_topology (tree.c:118)
==306445==    by 0x7B97FA9: nvme_scan (tree.c:177)
```
> tree: Fix leaking struct nvme_ns.generic_name

- src/nvme/ioctl.c
The original `lpo` info is lost in `nvme_get_log_page`. 
Save it into a local variable and append `offset` after it.
Signed-off-by: Jinliang Wang <jinliangw@google.com>
> ioctl: fix log page offset

- src/nvme/mi.c
According to NVMe Spec:
Command Dword 10 [23:16] : SPSP1
Command Dword 10 [15:08] : SPSP0
Signed-off-by: Jinliang Wang <jinliangw@google.com>
> mi: fix location of spsp1 and spsp0

- src/libnvme.map
- src/nvme/api-types.h
- src/nvme/ioctl.c
- src/nvme/ioctl.h
- src/nvme/types.h
Add required data structures and helper functions for TP4146 ("Flexible Data Placement").
These data structures and helpers are used by the associated [changes for nvme-cli](https://github.com/linux-nvme/nvme-cli/pull/1756), to be PR'ed separately.
> types: add fdp data structures and helpers

- src/libnvme-mi.map
Need to export nvme_mi_ep_set_timeout and nvme_mi_ep_get_timeout. These two functions were defined but left over in .map file.
Signed-off-by: Hao Jiang <jianghao@google.com>
> mi: add timeout functions to .map

- .github/workflows/meson.yml
- meson.build
- meson_options.txt
- subprojects/dbus.wrap
- subprojects/uuid.wrap
The dbus project supports to be consumed via Meson subproject mechanism.  Update the build configuration accordingly.
> build: Add support to build libdbus as fallback

- src/libnvme.map
- src/nvme/fabrics.c
- src/nvme/private.h
- src/nvme/tree.c
- src/nvme/tree.h
Adds setter and getter for tracking unique discovery controller. The current library design is a bit awkward, as we have logic outside of the library and inside, so we end up exposing such APIs.
> Add setter and getter to track unique discovery controller

- doc/config-schema.json.in
- src/libnvme.map
- src/nvme/json.c
- src/nvme/private.h
- src/nvme/tree.c
- src/nvme/tree.h
Allow to overwrite the system default Persistent Discovery Controller behavior via the config.json file.
> tree: Add persistent_discovery_ctrl config flag

- test/mi.c
We have a couple of cases in the MI test code where we're either not providing an initialised argument buffer, or a request with no data allocation.
These changes fix those cases, so we're a closer match to actual API usage, and avoid issues (like #563) from uninit arg data.
> test: mi: ensure we're providing full initialised buffers to the libnvme-mi API

- src/nvme/types.h
The timestamp member of nvme_fdp_event is a proper NVMe Timestamp, so use the actual data structure for it.
> types: use nvme_timestamp for fdp events

- src/nvme/fabrics.c
strchomp() has an off-by-one error and starts stripping spaces at the byte AFTER the end of the buffer.
See also https://github.com/linux-nvme/nvme-cli/pull/1780
> fabrics: Avoid buffer overrun in strchomp

- meson.build
With hardened distribution CFLAGS the meson code snippet wouldn't compile:
Compiler stderr:
```
.build/meson-private/tmpy2z1t5q4/testfile.c: In function 'main':
.build/meson-private/tmpy2z1t5q4/testfile.c:2:30: error: storage size of 'hints' isn't known
2 |              struct addrinfo hints, *result;
|                              ^~~~~
.build/meson-private/tmpy2z1t5q4/testfile.c:3:21: warning: implicit declaration of function 'getaddrinfo' [-Wimplicit-function-declaration]
3 |              return getaddrinfo(argv[1], argv[2], &hints, &result);
|                     ^~~~~~~~~~~
```
> build: Fix nss code snippet includes

- subprojects/dbus.wrap
The 'use list for dbus_static_flags' fix has been merged which adds support older version Meson.
https://gitlab.freedesktop.org/dbus/dbus/-/commit/cd1a9bb09a4e9330f8669fb6d385b1e095f97fc2
> build: Update dbus.wrap

- src/nvme/fabrics.c
strchomp() is handling the max length of a string correctly.
Reported-by: calebsander
Fixes: #https://github.com/linux-nvme/libnvme/pull/567#issuecomment-1419469773
> fabrics: Do not ignore one char whitespace when string sanitizing

- meson.build
The sysconfdir is an explicit path '/etc' and the muon implementation of join_paths is dropping the prefixdir, thus we need to string concanate the syscondfir path instead of using the join_paths function.
> build: Use prefixdir directly on sysconfdir

- meson.build
- meson_options.txt
- src/meson.build
- src/nvme/no-json.c
Make support for JSON related functionality optional again. Some embedded configuration do not want to have a lot of dependencies.
> build: Make json-c dependency optional again

- src/nvme/types.h
All the nvme defined payloads are in little endian. All the known users are already using the appropriate le*_to_cpu() accessors, so just fix the type annotations.
Cc: Klaus Jensen <its@irrelevant.dk>
Signed-off-by: Keith Busch <kbusch@kernel.org>
> types: fix endians

- src/libnvme-mi.map
- src/nvme/ioctl.c
- src/nvme/mi.c
- src/nvme/mi.h
mi: Add nvme_mi_admin_get_log_page
The non MI API has an nvme_get_log_page() function which accepts the
transfer length. In order to be able to use the nvme_get_log_page()
function ins nvme-cli, the MI API needs to provide the same API so that
the transport abstraction wrappers work.
See #https://github.com/linux-nvme/nvme-cli/issues/1818
> Add nvme mi get log page

- libnvme/nvme.i
- src/nvme/tree.c
With SWIG we create proxy classes to wrap the C structures (struct). These classes are used to create Python objects matching the C structures such as:
`nvme.root` is used to wrap `struct nvme_root`
`nvme.host` is used to wrap `struct nvme_host`
`nvme.ctrl` is used to wrap `struct nvme_ctrl`
etc...
One thing that SWIG cannot do is figure out the dependencies between the different objects. For example, it cannot tell that when deleting a host object that all the subsystems, controllers, namespaces under that host need to be deleted as well. That's an implicit property of the libnvme driver and users need to know to stop using objects after their parent has been deleted.
Unfotunately, with Python the Gargage Collector (GC) decides which objects to delete and it can delete obects in any …
> python: Fix segmentation fault during garbage collection

- libnvme/nvme.i
This is mainly a cosmetic change.
I've been wanting to do this for a while, but could never find the time. The SWIG file contains a lot of C code that was not following the standard formatting (e.g. indentation with tabs). I reformatted the code and moved a few things around to make it more readable.
> python: Reformat SWIG input file

- libnvme/meson.build
The option `-Dpython` takes 3 values: `auto`, `true`, or `false`. For `auto` (default), the Python bindings will be built if all the dependencies are met and will be skipped in not. For `true`, the Python bindings MUST be built and therefore missing dependencies need to be treated as errors. For `false`, the Python bindings won't be built whether the dependencies are met or not.
Currently, with `-Dpython=true`, if a dependency required to build the Python bindings is missing, meson silently skips it (i.e. it behaves like `-Dpython=auto`). This PR fixes that issue.
> python, meson: Assert that deps are present for -Dpython=true

- src/nvme/api-types.h
src/nvme/api-types.h:815: warning: Function parameter or member 'mos' not described in 'nvme_io_mgmt_recv_args'
src/nvme/api-types.h:815: warning: Function parameter or member 'mo' not described in 'nvme_io_mgmt_recv_args'
src/nvme/api-types.h:837: warning: Function parameter or member 'mos' not described in 'nvme_io_mgmt_send_args'
src/nvme/api-types.h:837: warning: Function parameter or member 'mo' not described in 'nvme_io_mgmt_send_args'
> doc: fix kernel-doc-check warning

- meson.build
The default sysconfdir needs to be initialize so that Meson and muon expand to the same final result using join_paths().
Fixes: f6100dd16b49 ("build: Use prefixdir directly on sysconfdir")
See https://github.com/linux-nvme/libnvme/issues/588
> build: Initialize sysconfdir

- meson.build
This is purely a cosmetic change. 
At the end of the `meson setup` command, display the options so that we can quickly determine that we've configured the project properly. For example:
```bash
...
------------------------------------------------------------
prefixdir:   /usr/local
sysconfdir:  /usr/local/etc
bindir:      /usr/local/bin
includedir:  /usr/local/include
datadir:     /usr/local/share
mandir:      /usr/local/share/man
libdir:      /usr/local/lib/x86_64-linux-gnu
------------------------------------------------------------
CONFIG_DBUS:  false
CONFIG_JSONC:  true
CONFIG_OPENSSL:  true
CONFIG_OPENSSL_3:  true
GIT_VERSION:  "1.3-27-g18d9b3c"
HAVE_BIG_ENDIAN:  0
HAVE_BSWAP_64:  1
HAVE_BUILTIN_TYPES_COMPATIBLE_P:  1
HAVE_BYTESWAP_H:  1
HAVE_ISBLANK:  1
HAVE_LIBNSS:  true …
```
> build, meson: Print option summary

- libnvme/nvme.i
I just found out that the DHCHAP Key can be set as a property (e.g. host.dhchap_key = "THE-KEY"). So, we can remove the set_key() method that was added a few days ago.
> python: Remove redundant host.set_key() method

- libnvme/nvme.i
Similar to the way we allow setting/getting the Host DHCHAP key, we need to allow setting/getting the Controller DHCHAP Key. There was already a "getter" property, but the "setter" property was missing.
> python: Add setter property for controller DHCHAP Key

- src/nvme/types.h
Add support for opcode field in error information log page based on TP
4113. It is easy to identify which command is associated with the error.
> types: add opcode field to error log page (TP4113)

- .github/workflows/build.yml
The test meson target builds only the necessary files for passing the test target. To build the complete library use the build target.
Sync with nvme-cli.
> build: Add build action back

- meson.build
- subprojects/json-c.wrap
- subprojects/openssl.wrap
The OpenSSL fallback is a bit tricky as we have a workaround in place to figure out if we are building against LibreSSL. If this is the case we can't use cc.has_header_symbol() and cc.has_header() for the fallback (aka internal).
> Update fallbacks to lastet available version

- doc/config-schema.json
- doc/rst/fabrics.rst
- meson.build
- meson_options.txt
- src/libnvme.map
- src/meson.build
- src/nvme/fabrics.c
- src/nvme/fabrics.h
- src/nvme/json.c
- src/nvme/linux.c
- src/nvme/linux.h
Here's an updated version of my patches for the upcoming TLS support for NVMe/TCP.
The first patch is function to store a TLS PSK in the specified keyring, and the other patches add support for the fabrics options 'keyring' and 'tls_key'.
Idea of these options are that the 'keyring' option references a keyring which holds all valid keys for this connection; the kernel code will then look up keys from this keyring and start the TLS connection with these keys.
The 'tls_key' option specifies a single key with which the kernel should start the TLS connection.
> Patches for TLS support (v2)

- src/nvme/fabrics.c
The TREQ field in the discover log page is actually a bit field, so we need to update the string mapping to print out all possible combinations correctly.
> Print out correct TREQ strings for discovery

- src/nvme/tree.c
nvme_bytes_to_lba() argument checker is ensuring that all passed in values are valid. That means we have at least one block to write, the offset is aligned to a block starting address and the number of blocks is a multiple of the block size
The last check is wrong, thus fix it.
Fixes #611
> tree: Fix argument check in nvme_bytes_to_lba

- doc/meson.build
- src/libnvme.h
- src/libnvme.map
- src/meson.build
- src/nvme/nbft.c
- src/nvme/nbft.h
Added support for parsing and printing the contents of the NBFT table (per NVMe-oF boot specification v1.0).
Signed-off-by: Stuart Hayes <stuart_hayes@dell.com>
Signed-off-by: Martin Wilck <mwilck@suse.com>
Signed-off-by: Tomas Bzatek <tbzatek@redhat.com>
Signed-off-by: John Meneghini <jmeneghi@redhat.com>
> nbft: added NBFT table support

- src/nvme/tree.c
Also offset modulo blocksize needs to be 0. Commit 01c6055e5602 ("tree: Fix argument check in nvme_bytes_to_lba") missed to update this, thus do it now.
Fixes #616
> tree: Fix offset argument check in nvme_bytes_to_lba

- .github/workflows/build.yml
- .github/workflows/release-python.yml
- meson.build
meson's default setting for wrap mode is to attempt to download missing
dependencies. Disable this feature as the community is unhappy with
this default behavior.
> Disable fallback on default

- src/libnvme.map
Now that the v1.4 release is out I assume the NBFT stuff is going to v1.5.
> nbft: Move added symbols to LIBNVME_1_5

- libnvme/tests/test-nbft.py
Since commit 1617d1a3f42a ("nbft: Parse the {HOSTID,HOSTNQN}_CONFIGURED flags") host_id_configured and host_nqn_configured are parsed. Thus we need to update the test case accordingly.
> python: Update test data

- libnvme/nvme.i
- libnvme/tests/test-nbft.py
I made the following changes so that the data is more Pythonic.
1) For boolean values, set them to `True`/`False` instead of `1`/`0`.
2) NBFT data contains ordered lists. In the raw NBFT data the position of each element in the list is indicated by a 1-based index. When converting to Python lists, make sure that each element is inserted in the list at the right position. This is done by converting the 1-based index to a 0-based index.
3) For objects that contain indexes referring to items in a list, make sure to convert the 1-based index to 0-based so that it can be used directly to access the python lists (e.g. `list[index]`).
4) Since Python lists are ordered (per 2 above), there is no need to keep an explicit 1-based index in each of the list items. Therefore those 1-based indexes were …
> Python: make NBFT data more pythonic

- src/nvme/ioctl.h
Older compilers complain with:
../src/nvme/ioctl.h:3063:2: sorry, unimplemented: non-trivial designated initializers not supported
Thus explicitly initialize all members of this data structure.
Fixes #632
> ioctl: Explicitly initialize all members of struct nvme_ns_mgmt_args

- examples/mi-mctp.c
In the mi-mctp example, we're incorrectly reporting the percent drive life used as the controller status. Fix the controller status output to use the correct (ccs) field.
> examples: fix incorrect controller status in MI info output

- libnvme/nvme.i
Ref: https://github.com/linux-nvme/libnvme/issues/634
> Python: Suppress swig warnings about unnamed struct

- src/libnvme-mi.map
- src/nvme/mi.c
- src/nvme/mi.h
Controllers may be scanned through nvme_mi_scan_ep, in which case the caller will not have access to the underlying controller IDs.
Add an accessor function to retrieve the controller ID for use in subsequent commands (like namespace attach).
> mi: Add nvme_mi_ctrl_id to retrieve controller ID

- src/nvme/types.h
This is to suppress warning on anonymous struct/union
Ref: https://github.com/linux-nvme/libnvme/issues/634
> python/swig: Wrap swig-sensitive struct inside #ifwdef SWIG

- libnvme/meson.build
The swig option `-py3` has been deprecated as of swig-4.1.0. A deprecation warning is printed when used with swig-4.1.0 or later.
> python/swig: Check swig version to determine whether -py3 is needed

- libnvme/nvme.i
Same fix as PR: https://github.com/linux-nvme/libnvme/pull/583
Prevent Garbage Collector (GC) from deleting host and root objects before all controller objects under that root/host have been GCed. This time, it's the init() method that needed the fix. Previously we had only fixed the connect() method.
> Python: Fix crash during garbage collection

- src/nvme/fabrics.c
In __nvmf_supported_option(), len is declared as size_t (unsigned)
"len = read()" may return a negative number;
the check "if (len < 0)" will always be false and therefore "buf[len]" will dereference an invalid memory address.
len should be declared as a signed size_t (ssize_t)
> fabrics: fix potential invalid memory access in __nvmf_supported_option()

- src/nvme/fabrics.c
From the NVMe base spec (version 2.0c, section 5.16.1.23):
> If the host reads the Discovery Log Page using multiple Get Log Page commands the host should ensure that there has not been a change in the contents of the data. The host should read the Discovery Log Page contents in order (i.e., with increasing Log Page Offset values) and then re-read the Generation Counter after the entire log page is transferred. If the Generation Counter does not match the original value read, the host should discard the log page read as the entries may be inconsistent.
`nvme_get_log_page()` will issue multiple Get Log Page commands to fetch the discovery log page if it exceeds 4 KB. Since GENCTR is at the start of the log page, this ordering is possible:
- GENCTR is read by a Get Log Page command for the …
> fabrics: check genctr after getting discovery entries

- examples/discover-loop.py
Running `examples/discover-loop.py` fails:
```
File "examples/discover-loop.py", line 59
c.disconnect()
^
IndentationError: expected an indented block after 'try' statement on line 58
```
> examples: Fix wrong indentation in discover-loop.py

- src/nvme/util.c
- src/nvme/util.h
- test/meson.build
- test/test-util.c
This is prep work for issue: https://github.com/linux-nvme/libnvme/issues/648
The new function `ipaddrs_eq()` can be used to compare IP addresses. Once https://github.com/linux-nvme/libnvme/pull/647 gets merged (assuming it does get merged), I will submit another PR to use `ipaddrs_eq()` everywhere that we compare IP addresses.
> util: Add ipaddrs_eq() to check whether two IP addresses are equal

- src/libnvme.map
- src/nvme/util.c
- src/nvme/util.h
- test/test-util.c
As per https://github.com/linux-nvme/libnvme/issues/648, make `nvme_ipaddrs_eq()`  public.
> util: rename ipaddrs_eq() to nvme_ipaddrs_eq() and make public.

- doc/config-schema.json.in
- libnvme/nvme.i
- src/libnvme.map
- src/nvme/fabrics.c
- src/nvme/json.c
- src/nvme/private.h
- src/nvme/tree.c
- src/nvme/tree.h
This patchset adds an 'application' string to both, the nvme root and the nvme subsystem.
With that an application can restrict lookup to subsystems which are managed  by that application.
For any application not setting the string during initialisation (ie does not call `nvme_root_set_application()`)
lookup will ignore subsystems which have an application string set.
Application strings are automatically set when creating new subsystems.
> Add 'application' strings to nvme_root and nvme_subsystem

- src/nvme/tree.c
Use `nvme_ipaddrs_eq()` to compare IP addresses. This is especially important for IPv6 addresses that can be expressed in upper or lower case, or in compressed or expanded form. For example the following two IP addresses are the same, but a simple string comparison would declare them to be different.
```
2001:0DB8:0000:0000:0000:FF00:0042:8329
```
is the same as
```
2001:0db8::ff00:0042:8329
```
> tree: Use nvme_ipaddrs_eq() to compare IP addresses

- src/nvme/fabrics.c
- src/nvme/util.h
The newly introduced feature to allow coexisting nvme-cli and nvme-stas needs some more tuning to get it working.
For example, we should also fitler out the well known discovery controllers.
> Extend execution context filtering

- scripts/build.sh
The build.sh file contains a mix of tabs and spaces, just use spaces consistently.
> scripts: Use spaces instead of tabs

- src/nvme/mi-mctp.c
If the poll() times-out or fails, we'll exit early from nvme_mi_mctp_submit still holding the tag reservation. When using an i2c transport, this may mean we hold a lock on the i2c bus with no way to release.
Instead, always drop the tag on function exit.
Fixes: 6a08780 ("mi-mctp: Add timeout support to MCTP transport")
> mi: don't return from mi_mctp_submit with a tag held

- src/nvme/tree.c
In nvme_ctrl_lookup_phy_slot(), we are missing a closedir(), which causes file descriptors to leak. Also, there was a missing free() when the function returns with ENOMEM.
> tree: missing closedir() causes fd leak for "/sys/bus/pci/slots"

- src/libnvme.map
- src/nvme/private.h
- src/nvme/tree.c
- src/nvme/tree.h
Don't open nvme devices while scanning the tree. Only open devices when we actually need to write commands to them.
This patch also provides functions to close fds when a user no longer needs them to be open.
Ref: https://github.com/linux-nvme/libnvme/issues/672
> tree: Don't open nvme devices until it's absolutely required

- src/nvme/mi-mctp.c
- src/nvme/mi.c
- test/mi-mctp.c
@birkelund has pointed out that a non-four-byte-aligned response to a MI command is possible; for example a Read MI Data (Controller List), when there are an even number of controllers and no padding applied.
This series allows unaligned responses; firstly we simplify the response handling code from using a scatter-gather buffer for the header/payload/MIC, to a simple linear buffer. Then we allow the unaligned response sizes for MI commands - both expected (where the caller provided an unaligned size) and unexpected (where the allocated size was aligned, but the response isn't).
@birkelund  - could you test this in your environment?
> Relax alignment requirements for MI responses

- src/libnvme.map
- src/nvme/private.h
- src/nvme/tree.c
- src/nvme/tree.h
Allow to retrieve the iopolicy settings for the subsystem.
See https://github.com/linux-nvme/nvme-cli/issues/1963
> tree: Add getter for subsystem iopolicy

- src/nvme/tree.c
With the recent change to scan all subsystems, 'nvme list-subsys /dev/nvmeXnY' now displays an annoying warning for the NQN mismatch for all other subsystems that don't match during the subsystem scan. For e.g.
NQN mismatch for subsystem 'nvme-subsys1'
NQN mismatch for subsystem 'nvme-subsys4'
nvme-subsys3 - NQN=nqn.1992-08.com.netapp:sn.48391d66c0a611ecaaa5d039ea165514:subsystem.subsys_CLIENT116_1
hostnqn=nqn.2014-08.org.nvmexpress:uuid:e6550026-173e-4959-ba74-be367844bd8a
\
+- nvme3 tcp traddr=192.168.1.116,trsvcid=4420,host_traddr=192.168.1.16,host_iface=eth5 live optimized
+- nvme7 tcp traddr=192.168.2.116,trsvcid=4420,host_traddr=192.168.2.16 live optimized
+- nvme8 tcp traddr=192.168.1.116,trsvcid=4420,host_traddr=192.168.2.16 live optimized
Avoid this warning by displaying it only …
> nvme-tree: avoid warning in 'list-subsys'

- README.md
OpenSSL is used for TLS over TCP whereas Keyutils is used for authentication.
Also fix spelling mistake: dependend -> dependent.
> doc: fix minor mistake in README.md about dependencies

- src/nvme/tree.c
The wrong nvme_subsystem struct was being passed to __nvme_subsystem_scan() which caused it to segfault. Fix it.
Fixes: d08fd10 ("make __nvme_scan_subsystem() returning bool")
> tree: fix segfault in nvme_scan_subsystem()

- test/ioctl/discovery.c
- test/ioctl/meson.build
- test/ioctl/mock.c
- test/ioctl/mock.h
- test/ioctl/util.c
- test/ioctl/util.h
- test/meson.build
Functions issuing admin/IO passthru ioctls sorely lack unit tests.
It would be great for unit tests not to need a real NVMe controller.
It's also useful to be able to test responses to commands
that might be impossible to trigger with real controllers.
To that end, implement infrastructure for mocking `ioctl()`,
allowing tests to set expectations for the NVMe passthru ioctls
that will be issued and control the corresponding responses.
The mock library can be used with `LD_PRELOAD` so that `libnvme`'s `ioctl()`
calls are redirected from `libc`. No changes to `libnvme` are needed.
Add unit tests for `nvmf_get_discovery_log()`.
They provide coverage of the logic in `nvme_discovery_log()`,
`nvme_get_log_page()`, and `nvme_get_log()` too.
The tests use the mock `ioctl()` infra to validate the …
> Test discovery log page functions by mocking NVMe passthru ioctls

- src/nvme/fabrics.c
Only retry a connect attempt with disable_sqflow if the kernel
actually supports this option.
Reported-by: Sagi Grimberg <sagi@grimberg.me>
> fabrics: Do not pass disable_sqflow if not supported

- internal/meson.build
- meson.build
When building libnvme as a subproject of another project (e.g. nvme-stas), the hard-coded absolute path to config.h, i.e. "-include internal/config.h" does not resolve properly and fails to build. Instead, use the real path calculated by meson and saved to variable "config_h".
> meson: Don't hard-code path to "internal/config.h"

- src/nvme/mi.h
- test/mi.c
According to the NVMe specification, Identify CNS value 15h ("Secondary Controller list of controllers associated with the primary controller processing the command") does not use the NSID field. So remove the "nsid" argument from
nvme_mi_admin_identify_secondary_ctrl_list().
Fixes: 07b63103878 ("ioctl: remove nsid from nvme_identify_secondary_ctrl_list()")
Fixes: https://github.com/linux-nvme/libnvme/issues/700
> mi: remove nsid from nvme_mi_admin_identify_secondary_ctrl_list()

- .github/workflows/build.yml
- .github/workflows/release-python.yml
The cross tool installation is breaking very often. Let's use a prebuild container for this.
> build: use prebuild container images for cross builds

- .github/workflows/build.yml
- .github/workflows/coverage.yml
- .github/workflows/release-python.yml
- scripts/build.sh
The coverage build also fails due missing dependency in install step. Let's use a prebuild container here as well.
> build: use container for coverage build

- .github/workflows/coverage.yml
The previous commit removed accidentally the checkout step. Add it back.
> build: checkout repo in coverage build

- .github/workflows/build.yml
- .github/workflows/coverage.yml
- .github/workflows/release-python.yml
We control the build containers so there is little risk that these randomly break. So let's go with the latest version and avoid updating the build files all the time.
> build: use latest container instead fixed version

- src/nvme/fabrics.c
- test/ioctl/discovery.c
- test/ioctl/util.c
- test/ioctl/util.h
`strchomp()` is only needed to strip trailing spaces from a string.
There is no need to replace `NUL` characters with `NUL` characters.
So simplify the check for "NUL or space" to just "space".
Update the function description as well,
as it doesn't strip all whitespace, just spaces.
The NVMe base specification defines fields TRSVCID and TRADDR
as "ASCII strings", meaning they are space-padded.
Therefore, whether spaces need to be stripped from them
doesn't depend on the transport or address family.
Some combinations already appear to be missing,
such as RDMA using IB addresses.
And if new transports are added in the future,
`sanitize_discovery_log_entry()` would need to be updated.
So strip spaces from these fields regardless of the entry's
transport type or address family.
The discovery …
> Account for discovery log page entry space stripping and simplify space stripping code

- src/libnvme.map
- src/nvme/fabrics.c
- src/nvme/private.h
- src/nvme/tree.c
- src/nvme/tree.h
- test/tree.c
There is duplicate code between **libnvme** and **nvme-cli**. When trying to instantiate a controller, both libnvme and nvme-cli scan the sysfs looking for an existing controller that can be reused.
This patch adds `nvme_ctrl_find()` and `nvme_ctrl_config_match()`. These functions can be used by nvme-cli to lookup existing controllers. This will allow removing the duplicate code in nvme-cli (separate commit to follow on the nvme-cli GitHub repo).
Note that some of the existing code had to be reorganized to make it possible for the new functions to reuse that existing code.
> tree: Add 2 new public functions to lookup existing controllers

- src/nvme/types.h
> Add support for the OAQD ID controller field

- src/nvme/ioctl.h
- src/nvme/mi.h
- src/nvme/types.h
This implements support for TP4119a, adding various fields and functions to enable better handling of the new Physical Receiver Eye Opening Measurement log page.
> Add support for Phy Rx Eye Opening Measurement Log

- meson.build
- meson_options.txt
- test/ioctl/mock.c
glibc has the following prototype for ioctl: int ioctl(int fd, unsigned long request, ...)
POSIX (inc. musl) has the following for ioctl: int ioctl(int fd, int request, ...)
Check which prototype is used in <sys/ioctl.h> to avoid a conflict and conditionally
define the right one for the system.
Bug: https://bugs.gentoo.org/914921
Signed-off-by: Sam James <sam@gentoo.org>
> test: handle POSIX ioctl prototype

- src/libnvme-mi.map
Last unused symbol, https://github.com/linux-nvme/libnvme/commit/20a3fa87520af7f615415091fe9da484b0ac3bd2 cleaned up the rest in libnvme.so.
```
clang  -o src/libnvme-mi.so.1.6.0 src/libnvme-mi.so.1.6.0.p/nvme_cleanup.c.o src/libnvme-mi.so.1.6.0.p/nvme_log.c.o src/libnvme-mi.so.1.6.0.p/nvme_mi.c.o src/libnvme-mi.so.1.6.0.p/nvme_mi-mctp.c.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libnvme-mi.so.1 -O3 -pipe -march=znver3 -flto=thin -Wl,-O1 -Wl,--as-needed -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0 ccan/libccan.a -Wl,--version-script=/var/tmp/portage/sys-libs/libnvme-1.6/work/libnvme-1.6/src/libnvme-mi.map /usr/lib64/libdbus-1.so -Wl,--end-group
ld.lld: error: version script assignment of 'LIBNVME_MI_1_1' to symbol 'nvme_mi_root_close' …
```
> build: remove symbol which doesn't exist in libnvme-mi.so

- src/nvme/private.h
- src/nvme/tree.c
- src/nvme/util.c
Related to https://github.com/linux-nvme/nvme-cli/pull/2051, there are a couple more ioctls made during the tree scan inside of libnvme. Last bits to fix the whole story, hopefully.
Noticed by https://bugs.archlinux.org/task/79760#comment222718
> tree: Allocate aligned payloads for namespace scan

- .github/workflows/coverage.yml
- .github/workflows/release-python.yml
- .github/workflows/release.yml
Only upload any artifacts to linux-nvme organization if it's NOT a fork.
> build: upload artifacts only for upstream repo

- src/nvme/ioctl.c
The spec defines these values on a bitwise basis within the shared 80-bit region, stored from MSB to LSB for each tag. Mechanically this can be achieved by setting the values as big-endian using the same logic currently in place.
Reviewed-by: Jeffrey Lien <jeff.lien@wdc.com>
Here's a link to discussion around fixing a similar issue with the copy command: https://github.com/linux-nvme/libnvme/pull/587
> ioctl: MSB variable-size storage/reference tags

- src/nvme/fabrics.c
The NVMe specfications are clear that the discovery log page entry SECTYPE field indicates whether TLS is supported.
Currently the TREQ field is used, which results in enabling TLS even when SECTYPE = "No Security" and TREQ = "Not required". Only enable TLS if SECTYPE indicates a TLS version is enabled.
From the NVMe/TCP transport specification, version 1.0c:
> Security Type (SECTYPE): Specifies the type of security used by the NVMe/TCP port. If SECTYPE is a value of 0h (No Security), then the host shall set up a normal TCP connection.
From TP8018:
> The SECTYPE value of 0h (No Security) specifies that TLS is not supported.
From TP8025 (the "TLS permitted" host case):
> If the SECTYPE field in the TSAS field in the discovery log entry for the remote entity is cleared to zero and the TSC …
> fabrics: use SECTYPE to determine whether to use TLS

- .github/workflows/build.yml
The build container already ships the Python toolchain, so there is no need to map the toolchain from the base container.
> build: do not setup python

- README.md
- src/nvme/mi.c
- src/nvme/nbft.c
- src/nvme/types.h
- test/ioctl/features.c
- test/ioctl/meson.build
- test/ioctl/mock.c
- test/meson.build
- test/mi-mctp.c
- test/mi.c
Testing out ASAN revealed that the new tests using `LD_PRELOAD` with a shared library containing mocks for libc functions cause ASAN to abort at startup. Suppress this check because ASAN seems to have no problems catching memory issues in `libnvme`, the tests, or the mocks.
Also fix several issues caught by enabling UBSAN in the unit tests:
- Passing NULL pointers to `memcmp()` and `memset()`
- Dereferencing unaligned pointers
- Overflow from bit shifts on `int` values that should be `u32`s
> Make ASAN work with tests mocking libc functions and fix several errors caught by UBSAN

- src/nvme/types.h
Bytes 1 and 2 are now defined as fields ETDAS and LBAFEE, so update the `struct nvme_feat_host_behavior` definition.
> types: add Host Behavior Support field definitions

- src/nvme/fabrics.c
- test/ioctl/discovery.c
Several improvements to fetching the discovery log page:
- Don't set the Retain Asynchronous Event bit. To ensure notifications aren't missed, this bit needs to be cleared on at least once Get Log Page command sent, which is not currently happening. The simplest solution is just to clear the bit in all commands, so do that.
- Avoid fetching the log page header twice in a row in case of a GENCTR mismatch
- Reduce the number of bytes of the header fetched from 1K to 20, since only the first 18 bytes currently have a defined meaning
- Implement `nvmf_get_discovery_log()` in terms of `nvmf_get_discovery_wargs()` to avoid code duplication
- Pass `struct nvme_get_discovery_args` instead of `struct nvme_get_log_args` to `nvme_discovery_log()`. This avoids confusion about which function is …
> Discovery log page optimizations

- src/nvme/nbft.c
Static checkers complain about memory leaks in the NBFT code.
> Fix a few memory leaks in libnvme

- src/nvme/linux.c
Fix to add the 2 byte length field to the HKDF-Expand-Label computation for retained and TLS PSK.
#735
> nvme: Add length field to Hkdf-Expand-Label computation

- scripts/build.sh
Several small improvements on the build script for the minimal build with muon. 
- don't rebuild samurai and muon everytime
- drop the dependency for the wrap feature
- fix build on older distros (from @ikegami-t )
> update build script

- src/libnvme.map
- src/meson.build
- src/nvme/base64.c
- src/nvme/base64.h
- src/nvme/linux.c
- src/nvme/linux.h
TP8018 specified a new version 1 for TLS identifiers, where the original (version 0) identifiers are suffixed with a PSK hash.
That allows for key rotation as the new identifiers will change whenever the key changes, thus allowing the client to request the correct key after a key rotation.
> Implement version 1 TLS identities as specified in TP8018

- src/nvme/types.h
Recent versions of nvme-cli have started reading vs from offset 392 instead of 384. Previous PRs coupled the use of nvme_id_ns for use in namespace management (create_ns).  However, the NVMe spec has a different structure for namespace management, with only a subset of the fields allowed/shared and some additional fields.
To fix this, remove lbstm and restore the proper length for vs from nvme_id_ns.
I expect that create_ns() should fully switch over to the nvme_ns_mgmt_host_sw_specified struct which seems aligned with the spec (though has some newer fields than what is available in the latest NVMe Command Set Specification Revision 1.0c). This will have to be addressed separately in nvme-cli.
https://github.com/linux-nvme/libnvme/pull/307
https://github.com/linux-nvme/nvme-cli/pull/1452
> types: fix regression for vendor-specific field in nvme_id_ns

- src/nvme/ioctl.c
Current `nvme_get_lba_status()` function does specify any `data_len` in the admin command, resulting in zero data being returned. Of the possible implementations described in #753 , this is the least intrusive change as it requires no update to nvme-cli.
If an alternative approach is preferred, please comment.
Closes #753
> Get LBA Status does not specify data_len; returning no data

- src/nvme/tree.c
The kernel already exposes parts or all attributes we are looking up
with the ns id command. By reading these from the sysfs we can remove
the last command we are issuing during the topology scan.
Depends on: https://lore.kernel.org/linux-nvme/20231218165954.29652-1-dwagner@suse.de/
Fixes: #681 #550
> tree: read all attributes from  sysfs when available

- internal/meson.build
meson reports:
internal/meson.build:25: DEPRECATION: Project uses feature that was
always broken, and is now deprecated since '1.3.0': str.format: Value
other than strings, integers, bools, options, dictionaries and lists
thereof.
Thus just hardcode the config file path
> build: construct path to config.h manually

- .github/workflows/build.yml
- libnvme/meson.build
- src/nvme/tree.c
- test/meson.build
- enable python build again
- fix memory corruption
Fixes: #762
> Fix memory corruption in tree.c

- src/nvme/fabrics.c
- src/nvme/linux.c
- src/nvme/tree.c
- src/nvme/util.c
Using the default, slightly hardened CFLAGS in Fedora I was getting a bunch of warnings like
```
In file included from ../src/nvme/linux.c:38:
In function ‘cleanup_fd’,
inlined from ‘__nvme_set_attr’ at ../src/nvme/linux.c:429:19,
inlined from ‘nvme_set_attr’ at ../src/nvme/linux.c:451:9:
../src/nvme/cleanup.h:37:17: warning: ‘fd’ may be used uninitialized [-Wmaybe-uninitialized]
37 |                 close(*fd);
|                 ^~~~~~~~~~
../src/nvme/linux.c: In function ‘nvme_set_attr’:
../src/nvme/linux.c:429:26: note: ‘fd’ was declared here
429 |         _cleanup_fd_ int fd ;
|                          ^~
```
With a default meson build, these are not reported, despite that the project sets `warning_level=1`, i.e. `-Wall`. Stripping the CFLAGS down it turned out the two `-O2 …
> cleanup: Explicitly initialize auto-cleanup variables

- meson.build
The 'join' function only takes one argument, so use the correct syntax here.
Fixes: 0cbda86c6035 ("build: handle patch level versioning")
> meson.build: fixup 'join' syntax

- src/nvme/linux.c
Running nvme check-tls-key hits a segfault as seen below:
nvme check-tls-key
-d NVMeTLSkey-1:01:bB7soUnpHfxVg53sCY21KY3nLbqLit2RcIO8Rbdf3mKhcKaM:
Segmentation fault (core dumped)
This is because the strlen check on subsysnqn or hostnqn crashes at src/nvme/linux.c due to either of them being null. Avoid this segfault by checking these strings before running a strlen on them.
> linux: avoid segfault in check-tls-key due to null hostnqn/subsysnqn

- src/nvme/tree.c
The kernel export the LBA size via the logical_block_size sysfs entry not the physical_block_size.
Fixes: 7959f52960fd ("tree: read all attributes from sysfs when available")
Fixes: https://github.com/linux-nvme/nvme-cli/issues/2173
> tree: use logical block size for lba

- src/nvme/mi.c
- test/mi.c
Before the fix, when we meet crc mismatch response, the errno is 0 and rc is 1. This combination will be mistaken as Admin Generic Command Status code value 0x1 (Invalid Command Opcode):
$ nvme id-ctrl mctp:1,20
crc mismatch
NVMe status: Invalid Command Opcode: A reserved coded value or an unsupported value in the command opcode field(0x1
After the fix, the rc is -1, and errno is set to Bad message.
$ nvme id-ctrl mctp:1,20
crc mismatch
identify controller: Bad message
> mi: set correct rc and errno when crc mismatch

- doc/config-schema.json.in
- src/nvme/fabrics.c
- src/nvme/fabrics.h
- src/nvme/json.c
- src/nvme/private.h
Add an option 'concat' to enable secure concatenation for TCP.
> fabrics: add 'concat' option

- src/nvme/types.h
Described by the NVM express base specification revision 2.0c.
> types: Add controller properties CMBEBS, CMBSWTP and NSSD

- src/nvme/tree.c
The scan operation is not atomically done and the sysfs might change while we are iterating over it. Thus, it's possible that we find a controller but when we try to lookup the corresponding subsystem it might already destroyed and removed.
This error makes blktests fail because it finds controllers controller which are not under control of blktests, instead they are created and destroyed by the udev auto connect rules.
These resources appear and disappear while the test runs but when we scan sysfs we issue errors for unrelated resources. Thus just do not issue a error, turn this into debug log message.
Anyway, we already do just return error codes for other reason in this function anyway without logging.
> tree: do not issue an error when subsys lookup fails during scanning

- src/nvme/linux.c
> linux: Explicitly initialize auto-cleanup variables

- src/nvme/types.h
The changes for PEL rci port identifier type print function.
> types: Add PEL reporting context port identifier type definitions

- src/nvme/fabrics.c
Do not pass to the is_dmi_uuid_valid() function an invalid len value if read() fails.
> fabrics: check the read() return value

- doc/config-schema.json.in
- src/libnvme.map
- src/meson.build
- src/nvme/crc32.c
- src/nvme/crc32.h
- src/nvme/fabrics.h
- src/nvme/json.c
- src/nvme/linux.c
- src/nvme/linux.h
- src/nvme/tree.c
Hey all,
this is my next attempt to implement persistent TLS key handling. The original idea of storing the key serial number in the JSON configuration file doesn't really work out as the key serial number is ephemeral, and might change whenever a key is updated/revoked or somesuch. So after a reboot the key won't be present, the we won't be able to load the keys at all.
With the pull request we now store the TLS keys in 'PSK interchange format' as mandated in the NVMe TCP transport specification, which then contains the actual key data. And, obviously, the parser has been updated to read the TLS keys
from the PSK interchange format, too.
The original pull request https://github.com/linux-nvme/libnvme/pull/783 would export all keys via the configuration file, thereby losing the …
> Persistent TLS keys take #2

- src/nvme/types.h
The changes for boot partition log print function.
> types: Add boot partition information definitions

- src/libnvme.map
Missing from the list of exports.
> libnvme: add missing symbol nvme_scan_tls_keys

- src/nvme/json.c
```
In file included from ../src/nvme/json.c:17:
In function ‘freep’,
inlined from ‘json_export_nvme_tls_key’ at ../src/nvme/json.c:70:24:
../src/nvme/cleanup.h:24:9: warning: ‘tls_str’ may be used uninitialized [-Wmaybe-uninitialized]
24 |         free(*(void **)p);
|         ^~~~~~~~~~~~~~~~~
../src/nvme/json.c: In function ‘json_export_nvme_tls_key’:
../src/nvme/json.c:70:38: note: ‘tls_str’ was declared here
70 |                 _cleanup_free_ char *tls_str;
|                                      ^~~~~~~
In function ‘freep’,
inlined from ‘json_export_nvme_tls_key’ at ../src/nvme/json.c:66:32:
../src/nvme/cleanup.h:24:9: warning: ‘key_data’ may be used uninitialized [-Wmaybe-uninitialized]
24 |         free(*(void **)p);
|         ^~~~~~~~~~~~~~~~~
../src/nvme/json.c: In function …
```
> json: Fix uninitialized variables

- src/meson.build
- src/nvme/fabrics.c
- src/nvme/filters.c
- src/nvme/private.h
- src/nvme/sysfs.c
- src/nvme/tree.c
11a0918 ("nvme: allow to overwrite base sysfs path") added support for changing the sysfs path via an environment variable. Unfortunately, it added a heap allocation
every time a sysfs path was requested.
Modify the callers to not free the paths, which allows a string constant to be returned if the path isn't overridden, avoiding an allocation. Cache the path in a static variable so that if it is overridden, the heap-allocated string only needs to be constructed once and afterwards can be reused.
Create a file sysfs.c to consolidate this logic
instead of spreading them across 3 files.
Also introduce a helper to factor out the duplicated code.
> sysfs: minimize heap allocations of sysfs paths

- .gitignore
The vscode directory was not in the .gitignore file. So add it.
> build: Add vscode directory into ignore

- meson.build
The meson 'debug' buildtype defaults to '-O0 -g' which misses some important compiler warnings (as of gcc-13). While there's no universal solution, the 'debugoptimized' buildtype supplies '-O2 -g' that appears to be a reasonable compromise for having important compiler warnings by default.
> build: Switch default meson buildtype to 'debugoptimized'

- src/nvme/types.h
Defined eye data present as bit 0 and printable eye present as bit 1. Fixed eye data present to bit 1 and printable eye present to bit 0. Add the optional data present reserved filed definition and macros to get.
> types: Fix EOM header optional data present fields definition

- src/nvme/ioctl.h
The existing nvme_ns_mgmt_delete() does not support the timeout.
> ioctl: Add nvme_ns_mgmt_delete_timeout()

- src/nvme/tree.c
Valgrind revealed a mem leak in nvme_ns_init() invoked by several nvme commands such as connect-all, list, disconnect-all, etc. Leak traced to the nvme_ns_id pointer not getting freed after use. Fix the same.
> tree: fix mem leak in nvme_ns_init()

- src/nvme/types.h
The existing NVME_CTRL_CMIC definitions are complex values.
> types: Add NVME_CMIC definitions

- src/nvme/util.c
for use through nvme_errno_to_string().
> util: Add string constant for ENVME_CONNECT_IGNORED

- src/nvme/types.h
Since missed to add the documentatin.
> types: Add enum nvme_unit/cmbebs/cmbswtp/flbas/cmic documentation

- examples/mi-mctp.c
Initialize net and eid variables to 0.
> examples: fix mi-mctp build warning errors

- src/nvme/types.h
- test/register.c
Incorrectly defined as PMRWMB.
Also add enum nvme_pmrcap documentation.
> types: Fix PMRWBM register name

- src/nvme/tree.c
The lba_size variable is of type int, thus we should use nvme_strtou32 and avoid overwriting memory.
Fixes: https://github.com/linux-nvme/libnvme/pull/825
> tree: use strtou32 to read lba_size

- src/nvme/types.h
> types: Added Command and Feature Lockdown LID

- examples/telemetry-listen.c
POSIX says that these constants are defined in sys/stat.h. On Linux with glibc and musl this is also defined in fcntl.h. Other systems define it only in sys/stat.h, so include that as well. The Linux headers ensure that the first of sys/stat.h or fcntl.h define the constant, so it's harmless to include both.
For the latest standard, IEEE Std 1003.1-2017, see https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/fcntl.h.html and
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/sys_stat.h.html for details.
> examples: Include sys/stat.h for S_I* constants

- src/nvme/mi.c
When returning a system error code (i.e. rc < 0), the function should return -1 and set errno instead of returning the errno directly. It is very helpful for the client to handle the rc in an unified way.
> mi: fix the return error code.

- src/nvme/base64.c
- src/nvme/linux.c
<stdint.h> provides `uint32_t`, while `u_int_32` is an unofficial/internal typedef that glibc happens to provide. This fixes the build on musl.
Bug: https://bugs.gentoo.org/931194
> Use C99 types for uint32_t

- ccan/ccan/endian/endian.h
[[ edited ]]
When both endian.h and ccan/endian/endian.h are included, we can have
__{BIG,LITTLE}_ENDIAN redefined when compiling with clang on FreeBSD.
Clang and gcc have moved to a predefine for endian orders. glibc defines
these the same as they are defied here, but that's an unsafe assumption
to make. Instead, only define them when __LITTLE_ENDIAN not defined as a
fallback to when the host does not define them in the standard system
headers.
> mi.h: Use ccan/endian/endian.h instead of endian.h

- src/nvme/mi.c
nvme_mi_scan_ep should return error code of calling function.
This will help the upper layer know the reason of failure.
> mi: fix the rc for nvme_mi_scan_ep

- src/libnvme.map
- src/nvme/json.c
- src/nvme/log.c
- src/nvme/log.h
- src/nvme/mi.c
- src/nvme/private.h
- src/nvme/tree.c
Let's refactor the logging out from the root object and accept the full defeat against no global variables fight.
> split logging from root object

- src/nvme/linux.c
- src/nvme/tree.c
In file included from ../src/nvme/linux.c:40:
In function ‘freep’,
inlined from ‘nvme_get_telemetry_log’ at ../src/nvme/linux.c:169:23:
../src/nvme/cleanup.h:24:9: warning: ‘log’ may be used uninitialized [-Wmaybe-uninitialized]
24 |         free(*(void **)p);
|         ^~~~~~~~~~~~~~~~~
../src/nvme/linux.c: In function ‘nvme_get_telemetry_log’:
../src/nvme/linux.c:169:30: note: ‘log’ was declared here
169 |         _cleanup_free_ void *log;
|                              ^~~
> linux: Fix uninitialized variables

- src/libnvme.map
- src/nvme/fabrics.c
- src/nvme/fabrics.h
- test/meson.build
- test/uriparser.c
This is an initial implementation for a simple URI parser. Described in NVM Express Boot Specification (TP8012), used in `struct nbft_info_discovery` as a composite connection string, as opposed e.g. to separate struct fields in `struct nbft_info_subsystem_ns`.
Open questions/TODO:
i.e. as defined in RFC 3986:
```
URI         = scheme ":" hier-part [ "?" query ] [ "#" fragment ]
foo://example.com:8042/over/there?name=ferret#nose
\_/   \______________/\_________/ \_________/ \__/
|           |            |            |        |
scheme     authority       path        query   fragment
```
Applied to NVMe:
```
nvme+tcp://user:pass@host:port/subsys_nqn/nid?name=ferret#nose
```
Since the above tasks may involve `struct nvme_fabrics_uri` element changes, marking as WIP, seeking initial feedback. …
> fabrics: Simple URI parser

- src/nvme/ioctl.c
be_reftag variable is in size of 64 bits, in case of reftag argument set to 1, be_reftag will be equal to 0x0100000000000000. (Since version 1.7 included cpu_to_be64() function) 
In case of NVME_NVM_PIF_16B_GUARD, bit masking the be_reftag above with 0xffffffff (size of cdw14) will clear the cdw14 to 0 causing some drives to not being able to set ILBRT/EILBRT.
I offer to shift be_reftag by 32 to the right so that drives can correctly set ILBRT/EILBRT field.
> ioctl: update nvme_set_var_size_tags() to properly use reftag

- src/nvme/mi-mctp.c
- src/nvme/mi.c
- src/nvme/private.h
- test/mi.c
Currently drive quirks are probed when opening a connection to the MI endpoint. The probe itself is the only IO that's required in the process of establishing the connection. We have an opportunity to make connection-establishment non-blocking if we can move the probe IO elsewhere.
We know the user is expecting IO to the endpoint when they issue a command. Given this, exploit the call to nvme_mi_submit() to establish the drive quirks.
> mi: Probe quirks on first command submission

- doc/conf.py.in
- scripts/release.sh
Let's reorder the release commits, so that the last commit is actually the version string update. The only reason for the previous order was the version string was used in the documentation. Though there are none, only the date is used.
Fixes: #832
> Change commit order on release

- src/libnvme.map
- src/nvme/ioctl.c
- src/nvme/ioctl.h
- src/nvme/mi.c
- src/nvme/mi.h
- test/ioctl/ana.c
- test/ioctl/meson.build
- test/ioctl/mock.c
- test/ioctl/mock.h
- test/test.c
The existing function `nvme_get_log_ana()` for fetching the ANA log
fills the provided ANA log page buffer in 4 KB increments.
This has two main drawbacks: it does not guarantee the log page is
fetched atomically, so the returned log page may be torn,
and it may read past the end of the ANA log page.
Not only does reading past the end of the log page entail
wasted commands and data transfers, the NVMe specification
says controllers should abort Get Log Page commands
that specify LPOL/LPOU values past the end of the log page.
nvme-cli sizes the ANA log page buffer based on the maximum
number of ANA groups and namespaces the controller supports,
which may be significantly larger than the current number.
Introduce a function `nvme_get_ana_log_atomic()` to fix these behaviors.
It parses the …
> Add support for atomic, piecewise ANA log fetch and fix bugs around ANA log functions

- src/libnvme-mi.map
- src/libnvme.map
- src/nvme/linux.c
- src/nvme/linux.h
A couple last changes required on top of #841 to allow `nvme-cli` to use this functionality
> ANA log page fixes, round 2

- src/nvme/util.c
if the "result" pointer is null because of a memory allocation failure, do not dereference it and do not free the old pointer.
> linux: avoid potential null pointer dereference

- src/nvme/mi-mctp.c
> mi-mctp: initialize the rc variable in handle_mctp_endpoint()

- src/nvme/types.h
The PEL feature added by NVMe revision 1.4 with the event types. But the event types were not implemented by the nvme-cli.
> types: add PEL vendor specific and TCG defined events definitions

- src/libnvme.map
- src/nvme/linux.c
- src/nvme/linux.h
Add a functio to revoke a TLS key from a keyring.
see #https://github.com/linux-nvme/nvme-cli/issues/2365
> linux: add nvme_revoke_tls_key

- src/nvme/types.h
As per TP4090, a new field support is added as NPDGL (Namespace Preferred Deallocate Granularity Large) and so the bit-field of NSFEAT, OPTPERF get extended by 1 bit.
Reviewed-by: Steven Seungcheol Lee <sc108.lee@samsung.com>
Reviewed-by: Mohit Kapoor <mohit.kap@samsung.com>
> types: add new field added in TP4090

- src/nvme/types.h
As per TP4090, a new field is added as MEM (MDTS and Size Limits Exclude Metadata) under nvme_id_ctrl_ctratt.
Reviewed-by: Steven Seungcheol Lee <sc108.lee@samsung.com>
Reviewed-by: Mohit Kapoor <mohit.kap@samsung.com>
> types: add new field added in TP4099

- src/nvme/types.h
As per TP4104, a new controller attribute support is added as HMBR (HMB Restrict Non-Operational Power State Access) under nvme_id_ctrl_ctratt.
Reviewed-by: Steven Seungcheol Lee <sc108.lee@samsung.com>
Reviewed-by: Mohit Kapoor <mohit.kap@samsung.com>
> types: Added new controller attribute as per TP4104

- src/nvme/linux.c
OpenSSL engines are not FIPS compatible and corresponding API is deprecated since OpenSSL 3.0. It appears this API is not actually used in the code, so remove it.
----
This is a wild shot and I wouldn't pretend I know what I'm doing. This simple change does however seem to do the trick. Tested only against openssl 3.0. Affects `nvme_gen_dhchap_key()`, tested through `nvme gen-dhchap-key`.
OpenSSL engine support is being removed from Fedora/CentOS Stream/RHEL.
> linux: Remove the use of OpenSSL Engine API

- src/nvme/tree.c
Not all directories have an address. Verify addr before calling strcmp().
Fixes: 42ac45359635 ("tree: Add PCI physical slot number for controller")
> tree: fix segfault in nvme_ctrl_lookup_phy_slot()

- src/nvme/types.h
Add the new fields added in TP4165 and enum for newly added action type. Also, modified the nvme_lba_status_atype enum documentation.
> types: add new fields added in TP4165

- src/nvme/tree.c
It should not touch errno but open() set value in json_read_config().
> tree: fix nvme_read_config() to not set errno if return 0

- scripts/build.sh
We had some fallouts which were happened at the install step when the documentation was build. Let's add this step, so we catch those errors in future.
Fixes: https://github.com/linux-nvme/nvme-cli/issues/2448
> build: add install step to doc CI build 

- src/nvme/types.h
As per TP4167, a new field is added as CSER (Command Submission and Execution Relaxations) under nvme_cmd_effects enum. Updated field value for NVME_CMD_EFFECTS_CSE_MASK as CSE takes 3 bits.
Reviewed-by: Mohit Kapoor <mohit.kap@samsung.com>
> types: Added new field CSER in enum as per TP4167

- src/nvme/linux.c
Treat only negative return values from derive_psk_digest () as errors.
> linux: Correct error handling for derive_psk_digest

- examples/mi-mctp.c
- src/libnvme-mi.map
- src/nvme/mi.c
- src/nvme/mi.h
The `breaked` command will left the SSD in Transmit Mode.
Add API to send the `abort` command to exit the Transmit Mode to
avoid the SSD being stuck in the Transmit Mode.
> mi: add service control primitive command

- src/nvme/ioctl.c
- src/nvme/ioctl.h
Use nvme_set_features_data, if setfeature use cdw11 and data field Use NVME_UUID_NONE instead of 0
> ioctl: refactoring set_features

- src/nvme/types.h
Add enum for Completion Condition (CMPC) field of Get LBA status command.
> types: Add enum for Completion Condition of Get LBA status command

- src/nvme/types.h
This checks the value to compare the field value and returns the result.
> types: add NVME_CHECK() definition to check nvme register field value

- .github/workflows/build.yml
- .github/workflows/coverage.yml
- .github/workflows/docs.yaml
- .github/workflows/release-python.yml
Use the pre build containers from linux-nvme/ci-containers.
> build: use linux-nvme/ci-containers

- src/nvme/types.h
- src/nvme/util.c
Adds definitions from the newly minted Live Migration specification (TP4159)
[TP4159 PCIe Infrastructure for Live Migration 2024.07.30 Ratified.pdf](https://github.com/user-attachments/files/17165615/TP4159.PCIe.Infrastructure.for.Live.Migration.2024.07.30.Ratified.pdf)
> types: Add TP4159 PCIe Infrastructure for Live Migration definitions

- src/nvme/ioctl.h
- src/nvme/mi.h
- src/nvme/types.h
Adding command APIs for inband, out of band, structures and enums for lockdown log page (LID : 0x14).
> libnvme: add lockdown log page support(LID : 0x14)

- src/nvme/types.h
Added enum for Sanitize Media Verification Event Support (SMVES) field in Persistent Event Log.
> types: Added enum for SMVES event of PEL log

- doc/config-schema.json.in
- src/libnvme.map
- src/nvme/fabrics.c
- src/nvme/fabrics.h
- src/nvme/json.c
- src/nvme/linux.c
- src/nvme/linux.h
- src/nvme/private.h
- src/nvme/tree.c
- src/nvme/tree.h
- src/nvme/util.c
- src/nvme/util.h
- test/config/config-diff.sh
- test/config/data/tls_key-1.json
- test/config/data/tls_key-1.out
- test/config/data/tls_key-2.json
- test/config/data/tls_key-2.out
- test/config/meson.build
- test/config/psk-json.c
- test/meson.build
- test/psk.c
Refactor and extend the PSK API and decouple the key store operations from the JSON parsing.
Fixes: #890
> TLS keys handling

- src/nvme/types.h
Supported the I/O command set specific indentify controller data structure fields below by NVMe 2.1.
1. version reporting
2. PCIe infrastructure for live migration
> types: add struct nvme_id_ctrl_nvm ver and lbamqf member variables

- src/nvme/json.c
- src/nvme/linux.c
- src/nvme/private.h
- src/nvme/tree.c
A couple of small fixes to make the recent TLS key handling work in all cases. 
The first commit addresses the problem that the TLS key would always added to the config output. This doesn't make sense if the user only provided `--tls` on the command line. Thus we can rip out all the export code triggered from the `nvme_dump_config` path.
Second commit addresses the problem that the JSON output was not identically with the input. The TLS keys got additional encoded. That's unnecessary and nvme-cli already disabled this for the JSON output, so we should properly also do this in libnvme.
> TLS key changes cleanups

- src/nvme/types.h
Add Estimated Time For Post-Verification Deallocation State (ETPVDS) and Sanitize State Information (SSI) fields of sanitize status log. Also, added enums required for future implementation.
TP4152 - Post-Sanitize Media Verification 2024.04.01 Ratified.
> types: Add ETPVDS and SSI fields of sanitize status log

- src/nvme/mi.c
Added support for variable length DLEN/DOFF for requests since it was only being handled for responses.
> Use Request or Response Length in DLEN and DOFF for MI

- .github/workflows/coverage.yml
The code coverage action is silently failing partly because the required Codecov token is missing.
Reading the token from the GitHub secrets.
The missing gpg package must be fixed in
https://github.com/linux-nvme/ci-containers.
Furthermore, fail the coverage workflow if the codecov-action errors out.
Please add the `CODECOV_TOKEN` to the GitHub secrets :)
> build: Add token for coverage test

- src/nvme/linux.c
__nvme_import_keys_from_config is helper to import the TLS keys. When we don't have OpenSSL builds enabled, this should be a no op. Thus don't return an error in this case.
Fixes: #https://github.com/linux-nvme/nvme-cli/issues/2555
> linux: do not return w/o OpenSSL support enabled

- src/nvme/types.h
Reservations and Host Identifier Interaction (RHII):
This bit indicates the reservations and
Host Identifier interaction support for the controller.
> types: Add id-ctrl CTRATT.RHII enum

- src/nvme/fabrics.c
- src/nvme/linux.c
The refactoring on the TLS handling introduced a regression. There shouldn't be any key store operations when TLS is not enabled nor if there is no key present. 
Fixes: #https://github.com/linux-nvme/nvme-cli/issues/2573
> Do not attempt to load keys if TLS is not enabled or if no keys is present

- test/ioctl/mock.c
On s390, tests which use the mock infrastructure fail, because all
unhandled ioctl are considered as fail. The tests issue kvm related
ioctls (0x7a). No need to fail or intercept them, just pass them thru to
the real ioctl.
> test/mock: pass thru unknown ioctls

- src/nvme/types.h
The field values added by NVM command set specification 1.1.
> types: add NVME_ID_CTRL_NVM_LBAMQF definitions

- meson.build
- test/ioctl/meson.build
- test/ioctl/mock.c
Older versions of glibc do not have dl as builtin in. Thus include libdl when it's available.
While at it also make the mock library to depend hard on the presents of dlsym. It's only necessary for s390.
Fixes: cbbfdd0ddfa2 ("test/mock: pass thru unknown ioctls")
Reported-by: Steven Seungcheol Lee <sc108.lee@samsung.com>
> tests: do not unconditionally depend on dlsym

- libnvme.spec.in
- meson.build
meson use default prefix with /usr/local
so rpm default macro defined installation directoy occur error
RPM build errors:
File not found: /root/rpmbuild/BUILDROOT/libnvme-1.11-0.x86_64/usr/lib64/libnvme*
To fix this use defined prefix from meson
#909
> rpm: use defined prefix from meson

- src/nvme/types.h
Added the enum for MAXWZD and NSZS bits of ONCS field in Identify Controller Data Structure and the enum for NSZ bit in the Write Zeroes command. TP4160 - WZSL Limit Modification.
> types: add enum for the fields added in TP4160

- src/nvme/ioctl.h
- src/nvme/linux.c
- src/nvme/linux.h
- src/nvme/types.h
MCDA added for Telemetry Host-Initiated Log creation
Log member variable added
Host-Initiated Log - THS
Controller-Initiated Log - TCS
> ioctl,types: telemetry log update based NVMe v2.1

- src/nvme/api-types.h
- src/nvme/types.h
Continues efforts from the newly minted TP4159 PCIe Infrastructure for Live Migration specification by adding additional types.
> types: Live Migration

- src/nvme/types.h
Boot Partition Capabilities (BPCAP)
NVM Subsystem Shutdown Latency (NSSL)
Power Loss Signaling Information (PLSI)
Controller Reachability Capabilities (CRCAP)
Key Per I/O Capabilities (KPIOC)
Maximum Processing Time for Firmware Activation Without Reset (MPTFAWR)
> types: Update id-ctrl field based on NVMe 2.1 spec

- src/nvme/types.h
NVMe specification specifies data in a little endian format
> types: use __le16 instead of __u16 for data fields

- src/libnvme.map
- src/nvme/api-types.h
- src/nvme/ioctl.c
- src/nvme/ioctl.h
Continues efforts from the newly minted TP4159 PCIe Infrastructure for Live Migration specification with new ioctls.
Same as #911 but adopts new types.h definitions from #913 and removes MOS derived arguments in favor of generic `mos` field. I figured this was more "future proof".
> ioctl: Live Migration

- src/nvme/types.h
Added the enum for SDSO and HIRS bits of Device Self-test Options field in the Identify Controller Data Structure and the newly added Self-Test Code (STC) of Device Self-test command.
TP4058 - Environmental Extremes Management
> types: add enum for the fields added in TP4058

- README.md
- meson.build
- meson_options.txt
- src/meson.build
- src/nvme/ioctl.c
- src/nvme/ioctl.h
- test/ioctl/mock.c
hello libnvme master,
io_uring on linux is pretty mature now, for the system with liburing, do the batch nvme_get_log by nvme uring cmd.
This change could gain about 10% performance improvement for some large log pages on my lab.
i believe the performance can be better if implement producer and consumer in two separated threads, if it's worth and acceptable, i can spend some time on this later.
thanks
> ioctl: get_log_page by nvme uring cmd

- src/nvme/types.h
This is to use libnvme register definitions instead of the shift operator.
> types: error information log entry status field definitions

- src/nvme/types.h
These changes to support for NVMe 2.1 features.
> types: Add NVMe 2.1 feature ID definitions

- src/nvme/ioctl.h
- src/nvme/types.h
This is to use for the endurance group scope log page.
> ioctl: add nvme_get_egid_log()

- src/nvme/types.h
Also mark struct nvme_feat_fdp_events_cwd11 as deprecated instead.
> types: add NVME_FEAT_FDPE_*** definitions

- src/nvme/types.h
Since supported by the NVMe 2.1.
> types: add I/O command fabric commands opcode definition

- src/libnvme-mi.map
- src/nvme/mi.c
- src/nvme/mi.h
- test/mi.c
Exposed an nvme_mi_mi_xfer for MI messages.  This is similar to the Admin passthrough, nvme_mi_admin_xfer.  
Added new API and test cases in test-mi
Signed-off-by: Chuck Horkin <chorkin@microsoft.com>
> mi_xfer: Added nvme_mi_mi_xfer API

- src/nvme/types.h
Add Key Per I/O Status (KPIOS) and Key Per I/O Data Access Alignment and Granularity (KPIODAAG) fields of Identify Namespace Data Structure added in NVM Command Set Specification 1.1.
> types: Update id-ns fields based on NVMe 2.1 spec

- src/nvme/types.h
Add NVME_CTRL_OACS_HMLM missed and also mask/shift/get definitions.
> types: add NVME_CTRL_OACS definitions

- src/nvme/types.h
Add Key Per I/O Capabilities (KPIOCAP) and Write Zeroes With Deallocate Size Limit (WZDSL) fields of I/O Command Set Specific Identify Controller Data Structure in NVM Command Set Specification 1.1.
> types: Update nvm-id-ns fields based on NVM Command Set Spec 1.1

- src/nvme/ioctl.h
Since the len parameter should be moved before the log parameter.
> ioctl: fix nvme_get_log_reachability_groups() parameters order

- src/nvme/types.h
Since the ngid variable name should be as rgid correctly.
> types: fix nvme_reachability_association_desc member variable name

- src/nvme/types.h
Add the Host Dispersed Namespace Support (HDISNS) field of Host Behavior Support feature.
NVM Express Base Specification 2.1
> types: add HDISNS field of Host Behavior Support feature

- src/nvme/mi.h
Since the len parameter should be moved before the log parameter.
> mi: fix nvme_mi_admin_get_log_reachability_groups() parameters order

- examples/telemetry-listen.c
- meson.build
- pyproject.toml
- src/nvme/linux.c
Dropping support for OpenSSL 1 and some cleanups for meson.build.
Fixes: https://github.com/linux-nvme/libnvme/issues/906
> Drop support for OpenSSL 1

- src/libnvme.map
The API function will be used by the host-discovery-log command.
> libnvme: export nvmf_exat_ptr_next

- internal/meson.build
- meson.build
- src/meson.build
- test/ioctl/meson.build
The python build breaks because of libnvme and the swig generator define variations of fallthrough. Let's only include the config.h for the libraries.
Fixes: #963
> build: do not include config.h globally

- Makefile
This pull request simply updates the meson syntax for some of the existing targets and provides a few additional targets as follows:
- For the "install" target, use "--skip-subprojects" so that only libnvme (and not the subprojects) get installed.
- For the "purge" target, add "meson subprojects purge".
- Added "update-subprojects" target
- Added "test-strict" target. This is to limit testing to libnvme and not all the subprojects.
> Makefile: Add new targets and update meson command syntax

- src/nvme/types.h
The values added in NVMe 2.1 specification.
> types: add SLM and CP command set indicator values

- libnvme/meson.build
- libnvme/nvme.i
Found that some controller attributes (e.g. tls_key) were missing from the SWIG wrapper code. Also found that for some of the attributes, SWIG was generating code that accessed to attributes directly instead of using the getter/setter methods.
For example, SWIG would generate code like this:
name = c->name;
Instead of that:
name = nvme_ctrl_get_name(c);
This may have been OK in most cases, but the Python code should really use the getter/setter methods instead of accessing the controller object directly.
SWIG is a weird beast to tame. For example, all the setter/getter methods must exactly match the syntax:
[class]_[member]_[set|get] (e.g. nvme_ctrl_traddr_get)
However, most of the libnvme functions follow this syntax:
[class]_[set|get]_[member] (e.g. nvme_ctrl_get_traddr)
The trick to …
> python, swig: add missing controller attributes

- .github/workflows/release-python.yml
Use the latest stable version of the action.
> build: fix python release workflows

- .github/workflows/release-python.yml
Enable back the python test release workflow again.
> build: enable python test release workflows

- .gitignore
- src/libnvme-mi.h
- src/libnvme.h
- src/nvme/api-types.h
- src/nvme/fabrics.h
- src/nvme/filters.h
- src/nvme/ioctl.h
- src/nvme/linux.h
- src/nvme/log.h
- src/nvme/mi.h
- src/nvme/nbft.h
- src/nvme/private.h
- src/nvme/tree.h
- src/nvme/util.h
- test/cpp.cc
- test/ioctl/ana.c
- test/ioctl/discovery.c
- test/ioctl/features.c
- test/ioctl/identify.c
- test/ioctl/meson.build
- test/ioctl/mock.c
- test/ioctl/util.c
The library header files should use the <> instead of "" for the includes.
> Use <> for includes 

- src/nvme/ioctl.c
The status code should be propagated like it is done for the ioctl interface.
Fixes: #980
> ioctl: return status code when using liburing

- test/ioctl/mock.c
Commit [ 0d8d0a55 build: do not include config.h globally ] changed to always pass -DHAVE_GLIBC_IOCTL=[0|1], and this causes a regression, for system without glibc ioctl, -DHAVE_GLIBC_IOCTL=0 is passed, and causes error:
../git/test/ioctl/mock.c:123:5: error: conflicting types for 'ioctl'; have 'int(int,  long unsigned int, ...)'
123 | int ioctl(int fd, unsigned long request, ...)
|     ^~~~~
In file included from ../git/test/ioctl/mock.c:9:
pathto/usr/include/sys/ioctl.h:115:5: note: previous declaration of 'ioctl' with type 'int(int,  int, ...)'
115 | int ioctl (int, int, ...);
Fixed by checking value of HAVE_GLIBC_IOCTL in mock.c
> mock.c: fix checking of HAVE_GLIBC_IOCTL

- src/nvme/types.h
This change fixes Sequence Indicator (SEQIND) Shift and Mask to match the NVM Express Base Specification, Revision 2.1.
The Mask and Shift are defined relative to Mos:
```
* @NVME_LM_SEQIND_SHIFT:			Shift amount to set Sequence Indicator (SEQIND)
*						field relative to MOS
* @NVME_LM_SEQIND_MASK:			Mask to set SEQIND field relative to MOS
```
Relative to Mos, the `SHIFT` should be 0 and `MASK` should be 0b11 (0x3).
> types: Fix Live Migration SEQIND Shift and Mask

- meson.build
- src/nvme/fabrics.c
When the system call fails with EINTR, retry the operation.
Fixes: #https://github.com/linux-nvme/nvme-cli/issues/2760
> fabrics: retry connect command on EINTR

- .github/workflows/release-python.yml
Use virtual python environment to install the packaging tool.
> build: fix python upload workflows

- .github/workflows/release-python.yml
Apparently the latest version of the action has a fix for the metadata problem.
> build: update gh-action-pypi-publish dependency

- .github/workflows/release-python.yml
- pyproject.toml
> build: switch to new python meson backend

- scripts/release.sh
- src/libnvme-mi.map
- src/libnvme.map
It is not obvious to start a new section after a release. Add an explicit new UNRELEASED section so contributers know where to put a new symbol.
I tried to get this done in awk and I really don't have a lot of experience with it. Yes, I asked a LLM to support me with it...
> Update the release script to update linker mapping file

- .readthedocs.yaml
The documentation build fails because the meson/ninja commands are outdated. Use the canonical way to build the sources.
> build: update readthedocs commands

- src/libnvme.map
- src/nvme/tree.c
- src/nvme/tree.h
Add a new routine to fetch the subsystem serial number.
> tree: add routine to fetch subsys serial number

- src/nvme/util.c
Since currently the feature length implemented in nvme-cli.
> util: add FDP events feature length

- examples/meson.build
- examples/mi-mctp-csi-test.c
- src/libnvme-mi.map
- src/nvme/mi.c
- src/nvme/mi.h
- src/nvme/private.h
- test/mi.c
These are used to send up to two concurrent requests over MI to the endpoint.
> mi: Add support for multiple csi buffers

- examples/meson.build
- examples/mi-mctp-ae.c
- src/libnvme-mi.map
- src/nvme/mi-mctp.c
- src/nvme/mi.c
- src/nvme/mi.h
- src/nvme/private.h
- test/mi-mctp.c
- test/mi.c
Added new functionality to mi.c and mi-mctp.c to handle AEMs.  Included new example mi-mctp-ae.c for usage.
> mi: Introduce asynchronous event message handling

- src/nvme/api-types.h
- src/nvme/ioctl.c
According to NVMe 2.1 Base Specificaiton, Controller Data Queue Size (CDQSIZE) occupies bits 31:00 of CDW12, so it should be using u32.
Note that in other places, like nvme-cli, the correct u32 is used: 
* [nvme-cli/plugins/lm/lm-nvme.c at master · linux-nvme/nvme-cli](https://github.com/linux-nvme/nvme-cli/blob/master/plugins/lm/lm-nvme.c#L67)
* [libnvme/src/nvme/ioctl.c at master · linux-nvme/libnvme](https://github.com/linux-nvme/libnvme/blob/master/src/nvme/ioctl.c#L2325)
> types: Change LM CDQ sz argument from u8 to u32.

- Makefile
- meson.build
First make the clean target behave like purge. That is what most autotools users expect.
Second, get the static build going again.
> makefile fixes

- examples/meson.build
- meson.build
The fix required for the muon build on CentOS.
> mi: fix missing braces around initializer warnings

- src/nvme/tree.c
When trying to determine if a candidate configuration matches an existing controller connection, treat the candidate's host_iface or host_traddr set to "none" as a NULL pointer.
This is to avoid using host_iface/host_traddr in the comparison with existing connections and falsely concluding that a new connection needs to be created.
This should fix issue: https://github.com/linux-nvme/nvme-cli/issues/2824
> tree: handle the case when host_iface/host_traddr are set to "none"

- examples/mi-mctp-csi-test.c
The <bits/*.h> header files are GNU libc specific, and should not be used directly from application code. This one in particular is already included by <pthread.h> on glibc.
Fixes build on musl.
See also #1014.
> examples: remove unnecessary include of <bits/pthreadtypes.h>

- test/ioctl/identify.c
- test/ioctl/logs.c
- test/ioctl/meson.build
This PR adds tests for log functions defined in ioctl.h and adds the missing tests for the identify functions defined in ioctl.h.
> Expanding test coverage for ioctl.h functions

- test/ioctl/meson.build
- test/ioctl/zns.c
Use the mock ioctl infrastructure to test the functions in ioctl.h that issue zns commands.
> test: add tests for zns functions

- src/nvme/mi.c
- test/mi.c
MI commands may be unaligned and also have payloads that are being sent and recieved at the same command.  One case of this is AEM Sync. This wasn't seen before because that particular path does not use nvme_mi_mi_xfer().
> mi:     nvme_mi_mi_xfer() is overly restrictive

- README.md
- meson_options.txt
The Get Log Page command can be used with io_uring. However, the way it is implemented is highly questionable. In other words, it's a bit crazy.
Therefore, do not enable it unless you fully understand what you're doing.
> build: disable liburing support per default

- test/ioctl/meson.build
- test/ioctl/misc.c
Use the mock ioctl infrastructure to test the functions in ioctl.h that issue miscellaneous ioctl commands.
> test: add tests for miscellaneous ioctl functions

- src/nvme/ioctl.c
- src/nvme/types.h
While the NVMe standard defines the Controller Data Queue command's CNTLID field as bits 15:00, this field is offset into CDW11 by the Create Queue Specific (CQS) field in bits 31:16, making the existing CDW format incorrect
Define the `NVME_LM_CQS_SHIFT` and `NVME_LM_CQS_MASK` fields and use the in the `nvme_lm_cdq` ioctl.
> types: Add Create Queue Specific (CQS) shift and mask for LM CDQ command

- src/nvme/tree.c
The trl object can be reused, thus all resources should be freed first.
Suggested-by: Martin George <marting@netapp.com>
Fixes: #1028
> tree: free ctrl attributes when (re)configure ctrl

- src/nvme/mi.c
- src/nvme/tree.c
As per the POSIX manual, free() is NULL-safe i.e. we could call it without first checking whether the respective pointer is non-NULL. So apply that here. And while at it, reorder some of the _cleanup_free_ items in the declaration section.
Suggested-by: Martin Belanger <martin.belanger@dell.com>
> tree: sanitize free() handling

- src/libnvme.map
- src/nvme/mi.c
- src/nvme/mi.h
The set feature is prohibited for the managemnet endpoint support.
> mi: add arbitration feature get function

- src/nvme/linux.c
I was attempting to debug connecting the Linux driver / libnvme /
ktls-utils host stack to the SPDK nvmf_tgt over TLS, and ran into some
issues.
The TLS connection fails to complete a handshake because the TLS PSKs
are different. The NVMe/TCP specified key derivation steps from the
configured interchange format, to a retained PSK and finally the TLS
PSK, is implemented incompatibly in libnvme and SPDK.  After some
investigation, I believe the SPDK implementation to be correct and am
providing a libnvme patch to match it. With libnvme modified, I see the
TLS handshake complete in tlshd.
> linux: TLS PSK derivation fixes

- src/nvme/json.c
- src/nvme/tree.c
The current logic will not set the host secret to the controller when
the sysfs value and the value from the host object are identically.
Thus, if the controller has a host key us this one and add it to
controller, if missing try to use the one from the host object.
Signed-off-by: Daniel Wagner <wagi@kernel.org>
> tree: always set the host key

- src/libnvme.map
- src/nvme/linux.c
- src/nvme/linux.h
To retrieve telemetry log data area 4, the Extended Telemetry Data Area 4 Supported in the Host Behavior Support feature needs to be set.  The bit will be cleared after the log has been retrieved.  This commit will add functions to set and clear that bit.
[wagi: - added changed argument to clear function
- refactored error handling (return early)]
substituted : #1044
> linux:  Add functions to set and clear etdas bit

- src/libnvme.map
- src/nvme/linux.c
- src/nvme/linux.h
- test/psk.c
Hi all,
here's my attempt to fixup the HKDF-Expand-Label algorithm. The first patch (from Chris Leech) implements the RFC-conformant algorithm for HKDF-Expand-Label, and the second patch adds back the original implementation via a new function nvme_import_tls_key_compat()
> Fixup HKDF-Expand-Label algorithm

- doc/meson.build
The api-types.h file was not included during documentation generation, thus not being available in the online doc. It was containing some important structures used as arguments for some function calls.
> docs: add missing API types documentation

- examples/discover-loop.py
- libnvme/nvme.i
I found a rather stupid typo in nvme:discover, and to ensure we catch similar issues going forward I've also added a python discovery script.
> Fixes for python discovery

- src/nvme/linux.c
Add a fallback implementation for nvme_insert_tls_key_compat() if CONFIG_KEYUTILS is not set.
> nvme/linux: add fallback implementation for nvme_insert_tls_key_compat()

- examples/discover-loop.py
This is just a minor fix to the example code.
In the example, when ctrl.discover() fails, we should not invoke sys.exit() immediately, but instead allow the ctrl.disconnect() to be invoked.
> python: Don't exit immediately on discovery fail.

- meson.build
- src/nvme/linux.c
- test/hkdf_add1.c
- test/meson.build
linux: use EVP_PKEY_CTX_add1_hkdf_info only once in compat function
OpenSSL prior to 3.3.1 had an issue with EVP_PKEY_CTX_add1_hkdf_info()
where it acted like a 'set1' function instead of an 'add1' as
documented.  Work around that by building the entire info vector outside
of the OpenSSL API and only calling this function once.
This is the same workaround used in commit eff0ffef0273 ("linux: fix
HKDF TLS key derivation back to OpenSSL 3.0.8").
Signed-off-by: Daniel Wagner <wagi@kernel.org>
Fixes: #1053
> linux: use EVP_PKEY_CTX_add1_hkdf_info only once in compat function
