linux-nvme/libnvme

configure
examples/discover-loop.c
examples/display-columnar.c
examples/display-tree.c
examples/telemetry-listen.c
src/Makefile
src/nvme/fabrics.c
src/nvme/fabrics.h
src/nvme/json.c
src/nvme/private.h
src/nvme/tree.c
src/nvme/tree.h
src/nvme/util.c
test/Makefile
test/cpp.cc
test/test.c
test/zns.c

This patchset implement per-controller configuration, by implementing an internal configuration tree.
This internal configuration can then be read from or written to a JSON configuration file.

Per-controller configuration support

---

examples/discover-loop.c
src/Makefile
src/libnvme.h
src/nvme/cleanup.c
src/nvme/cleanup.h
src/nvme/fabrics.c
src/nvme/fabrics.h
src/nvme/ioctl.c
src/nvme/ioctl.h
src/nvme/json.c
src/nvme/log.c
src/nvme/log.h
src/nvme/tree.c
src/nvme/tree.h
src/nvme/types.h
src/nvme/util.c
test/test.c

This patchset contains some fixes/updates from nvme-cli to allow for an integration of nvme-cli on top of libnvme.

Preparation for nvme-cli integration

---

src/Makefile
src/nvme/fabrics.c
src/nvme/libnvme.i
src/nvme/log.c
src/nvme/log.h
src/nvme/tree.c

Here's a patchset to improve logging for the python binding, and also some minor fixes for issues found during testing.

Improve logging and minor fixes

---

src/nvme/fabrics.c
src/nvme/json.c
src/nvme/tree.c
src/nvme/tree.h

Heya,
here are some fixes which cropped up during testing persistent discovery controllers; please apply.
(As they are required for the fixes on the nvme-cli side).

Discovery fixes

---

src/nvme/tree.c

Fixed double free (which causes things to crash) and fixed a few memory leaks.

Fix memory leaks and double free

---

src/nvme/fabrics.c

IBM POWER systems expose a platform created UUID in the device
tree. Use that as the UUID in the host NQN
Signed-Off-by: Wen Xiong <wenxiong@linux.vnet.ibm.com>
Reviewed-by: Brian King <brking@linux.vnet.ibm.com>

nvme-cli: nvme gen-hostnqn use partition UUID on IBM POWER

---

Makefile
pynvme/Makefile

Use setup.py to install the binding to the sitearch.

pynvme: Add install target to Makefile

---

src/nvme/ioctl.c
src/nvme/ioctl.h

Signed-off-by: Andreas Hindborg <andreas.hindborg@wdc.com>

Fix a bug where CSI was not passed to to nvme_ns_mgmt

---

src/nvme/types.h

Signed-off-by: Klaus Jensen <k.jensen@samsung.com>

types: add NVME_CAP_CSS_CSI

---

src/nvme/fabrics.c
src/nvme/private.h
src/nvme/tree.c
src/nvme/tree.h

Small patch set to cleanup the list of exported symbols.

Cleanup exported symbols

---

src/nvme/tree.c

Fix host_iface offset.
Just a copy-paste typo.

Fix host_iface offset.

---

doc/config-schema.json

Add a schema file to describe the JSON configuration file format.

Add json config schema

---

doc/config-schema.json
libnvme/nvme.i
src/nvme/fabrics.c
src/nvme/fabrics.h
src/nvme/json.c
src/nvme/private.h
src/nvme/tree.c
src/nvme/tree.h
src/nvme/types.h

Hi all,
here's a patchset to support TP8013 (unique discovery controller identification) and TP8014 (discovery controller discovery).
The kernel parts are already merged.

TP8013 & 8014 support

---

src/nvme/log.h

log: fixup SPDX license

---

doc/config-schema.json

Add the authentication key definitions to the JSON schema.

Add authentication keys to JSON schema

---

src/nvme/tree.c

'loop' controllers have an empty 'address' sysfs attribute, so we
need to check for loop to avoid failures due to an invalid controller
address.

tree: fixup loop address handling

---

.gitignore

we just need to maintain .wrap files for dependencies

build: Add subpackages contents to .gitignore

---

src/nvme/fabrics.c

Some settings like 'ctrl_loss_tmo' accept '-1' as valid values, so we need to fixup add_int_argument() to handle it correctly.
And a '-1' does not imply 'unset', so we shouldn't assume that.

Fix up handling of '-1' values

---

doc/libnvme.rst
doc/man/enum nvme_cmd_get_log_lid.2
src/nvme/ioctl.h
src/nvme/types.h

nvme: Add Media Unit Status log page(LID: 0x10)

---

src/nvme/tree.c

Opening the controller device will fail if the controller is resetting,
so trying to open it during controller initialisation will fail, and
the controller will not displayed correctly.
So only try to open the controller device if required, allowing the
initialisation to continue.

tree: only open controller device node if required

---

doc/man/nvmf_add_ctrl_opts.2
src/libnvme.map
src/nvme/fabrics.c
src/nvme/fabrics.h

Some minor cleanups for RC; removing an obsolete function and updating documentation for fabrics.h

Cleanups for release candidate

---

src/nvme/ioctl.h
src/nvme/types.h

Cleanup patch as per the discussion in PR#199

Clean up Patch for types.h, ioctl.h

---

doc/libnvme.rst
doc/man/nvme_path_get_subsystem.2
doc/man/nvme_reset_topology.2
src/libnvme.map
src/nvme/tree.c
src/nvme/tree.h

Document all prototypes in src/nvme/tree.h and remove duplicate or unused functions.

Document function prototypes

---

doc/libnvme.rst
src/nvme/fabrics.c
src/nvme/ioctl.h
src/nvme/linux.h
src/nvme/tree.h
src/nvme/types.h
src/nvme/util.h

Run kernel-doc over the source files and update comments to keep sphinx happy.

Sanitize kernel-doc comments

---

doc/meson.build

Fix license info

---

src/nvme/ioctl.h
src/nvme/types.h

Reviewed-by: Steven Seungcheol Lee <sc108.lee@samsung.com>

nvme: Add Supported Capacity Configuration List log page(LID: 0x11)

---

meson.build
src/nvme/json.c
src/nvme/tree.c

We already have a json-c subproject, so we should make json-c mandatory during build.

Make JSON-C mandatory

---

src/nvme/linux.h
src/nvme/log.h
src/nvme/tree.h

Cleanup patch for linux.h, log.h, tree.h

---

src/nvme/types.h

Added structure field usage details in doc section for ZNS

types.h: doc update for ZNS structures

---

doc/config-schema.json
libnvme/nvme.i
src/libnvme.map
src/nvme/fabrics.c
src/nvme/fabrics.h
src/nvme/ioctl.c
src/nvme/ioctl.h
src/nvme/json.c
src/nvme/private.h
src/nvme/tree.c
src/nvme/tree.h
src/nvme/types.h
src/nvme/util.c
src/nvme/util.h

This is based on #243 with a lot of small nitpicking cleanups and refactoring things (see also my initial review in #241).
Note: I also renamed a lot of the types to match with what is written in the spec.
@martin-belanger I haven't tested this yet. I am trying to get a test setup running. In case you have time to give this a go I would really appreciate it.

TP8010 support refactored

---

src/nvme/types.h

Added missing doc field description for NVM commands and Feature Identifiers

types: doc field update for NVM commands, Feature Identifiers

---

src/nvme/types.h

Management Interface command related structure field description has been updated in the doc section.

types: All MI command related structure doc field update

---

src/nvme/types.h

updated enum field documentation for all admin opcodes, feature identifiers, log pages, identify commands

types: Add doc field for admin opcodes, FIDs, LIDs, Identify commands

---

.github/workflows/python-publish.yml

CI: rename branch main to master

---

src/nvme/util.c

Added status code values in respective error codes in order to return proper error no

util: Add status code values in order to return errno

---

src/nvme/types.h

updated missing doc field description for returns.

types: Add missing doc field description

---

.github/workflows/meson.yml

will rebase after #280 is merged

CI: add test for subproject fallbacks compilation

---

src/nvme/tree.c

When the user doesn't provide trsvcid always use the default values
for tcp/rdma transport.
Fixes: #295

tree: Add support for default trsvcid for all controllers

---

src/nvme/fabrics.h
src/nvme/ioctl.c

Aligning whitespace indentation and function arguments indentation
with braces.

Streamlining documentation

---

src/nvme/fabrics.c
src/nvme/tree.c

Misc. static analyzer fixes

---

README.md

readme: Add github badges

---

src/nvme/ioctl.h
src/nvme/types.h

Added interface to get MI Command supported_effects log page
Added Telemetry Host-Initiated Data Generation Number nvme_telemetry_log struct
Added ehai and pelpid fields to the nvme_persistent_event_entry struct
Added NVME_IDENTIFY_CNS_CSI_ID_NS_DATA_STRUCTURE/0x1B define

Nvme 2.0 Changes 

---

src/libnvme.map
src/nvme/types.h
src/nvme/util.c
src/nvme/util.h

Signed-off-by: Brandon Paupore <brandon.paupore@wdc.com>

Add lbstm support for create-ns

---

src/nvme/tree.c

Fixup scan filter usage and a debugging messages during scanning.

Fixup scan filter usage

---

src/nvme/filters.h
src/nvme/ioctl.h

CI has been complaining, so fix things up.

Update function prototype documentation

---

doc/installation.rst

doc: update installation doc

---

.github/workflows/meson.yml
meson.build
subprojects/uuid.wrap

from https://github.com/util-linux/util-linux/pull/1654
and https://github.com/util-linux/util-linux/pull/1657

build: use uuid wrap for fallback build

---

.github/workflows/meson.yml

Now possible since we can use uuid for fallback

ci: add static library compilation

---

src/nvme/ioctl.c

Signed-off-by: Jeff Lien <jeff.lien@wdc.com>

ioctl: Fix STC mask for device-self-test command

---

src/nvme/fabrics.c

Move the initial header read into the do while loop. This simplifies
the loop flow into first read header if there are records fetch them
too.
With this we keep the genctr and numrec in sync for both get log
invocation.
Fixes: #https://github.com/linux-nvme/nvme-cli/issues/1555
```bash
localhost:~/nvme-cli # .build/nvme discover -t tcp -a 10.162.198.42 -vvvv
Error opening /etc/nvme/config.json, No such file or directory
connect ctrl, 'nqn=nqn.2014-08.org.nvmexpress.discovery,transport=tcp,traddr=10.162.198.42,trsvcid=8009,hostnqn=nqn.2014-08.org.nvmexpress:uuid:2cd2c43b-a90a-45c1-a8cd-86b33ab273b5,hostid=2cd2c43b-a90a-45c1-a8cd-86b33ab273b5,ctrl_loss_tmo=600'
connect ctrl, response 'instance=0,cntlid=1'
nvme0: ctrl connected
lookup subsystem …
```

fabrics: restructrure nvmf_get_discovery_log

---

.github/workflows/release.yml
release.sh

Automate the release with a script. This ensures we always do the same steps for an release. It also documents how to do it.
Fixes: #287

Add release script

---

doc/meson.build

Fix two regressions in the doc building process.
See #414

Fix doc build

---

examples/discover-loop.c

examples: Add missing free()

---

src/nvme/mi.c

Currently, every admin command function has a similar pattern for catching an error from one of:
- the MI transport; or
- the admin cdw0 field, sometimes populated to a result pointer
This change adds a helper for that pattern.
Then, instead of using cdw0 for the return value, we should be using cdw3 instead, as cdw0 is command-specific, and may not always indicate an error. We can then return the proper status type & status, in the same way that the ioctl commands do.
This goes part way to fixing
https://github.com/linux-nvme/libnvme/issues/456, but we still have an issue where the MI return values may alias the cdw3 return values.

mi: Introduce a helper for response status, unify values with ioctls

---

src/nvme/fabrics.c

fabrics: Filter out empty strings in add_argument()

---

.github/cross/ubuntu-static.txt
.github/workflows/meson.yml
meson.build
src/nvme/util.c

Support static builds

---

.github/cross/ubuntu-s390x.txt
.github/workflows/meson.yml

Let's add s390x so that we have a big endian target.

Add s390x cross build

---

src/nvme/mi.c

rename the `tmp` variable into `xfered_size`.
It is hard to figure out a name which can imply that this variable is used as both input and output parameter, so I choose `xfered_size` to emphasize the output functionality.
Signed-off-by: Jinliang Wang <jinliangw@google.com>

mi: rename tmp variable inside nvme_mi_admin_get_log

---

src/nvme/mi.c
test/mi.c

mi: use correct log page offset
Problem:
The usage of `doff` in `nvme_mi_admin_get_log` is wrong.  It will cause below error:
```
Admin request:
opcode: 0x02
flags:  0x03
ctrl:   0x0000
nsid:   0x00000000
cdw2:   0x00000000
cdw3:   0x00000000
cdw4:   0x00000000
cdw5:   0x00000000
doff:   0x00001000
olen:   0x00001000
cdw10:  0x03ff8007
cdw11:  0x00000000
cdw12:  0x00000000
cdw13:  0x00000000
cdw14:  0x00000000
cdw15:  0x00000000
Admin response:
Status: 0x04
cdw0:   0x677830c7
cdw1:   0x00000000
cdw3:   0x00000000
data_len: 0x00000000
NVMe-MI status: Invalid Parameter(0x4)
``` 
This GetLogPage Admin Command requests to read Log Page 0x07, `lpo` = 0, length = 4KB
However, the `doff` and `olen` requests NVMe controller skip the first 4KB, and return the next 4KB.
We should set `doff` to 0, …

mi: use correct log page offset

---

src/nvme/ioctl.h

A couple of fixes for the TP4146 Flexible Data Placement support.

TP4146 updates

---

meson.build
src/nvme/fabrics.c
src/nvme/ioctl.h
src/nvme/tree.c
src/nvme/util.c
src/nvme/util.h

A bunch of fixes/improvements which are from the #556  work. Let's review them independently from the new feature.

Miscellaneous fabric fixes/improvements

---

src/nvme/fabrics.c

Do not just sanitize the traddr and trsvcid when unsing the auto discovery/connect path, instead also do it for all users of nvmf_get_discovery_log{_args}() per default.
See also #561

fabrics: Always sanitize discovery log entries

---

src/nvme/types.h

Signed-off-by: Tokunori Ikegami <ikegami.t@gmail.com>

types: Add abort self-test code value definition

---

.github/workflows/build.yml
.github/workflows/meson.yml
.github/workflows/muon.yml
meson_options.txt

- Update the defaults for libdbus
- Add a new minimal dependency build target using muon instead Meson.

Update build settings and add additional CI targets

---

libnvme/nvme.i

Add the ability to set/get the Host Key.
Add Python wrappers for `nvmf_hostnqn_from_file()` and `nvmf_hostid_from_file()`

Python: Add a few new APIs

---

src/nvme/tree.c

If scan_namespace is called with a generic device (e.g., /dev/ng0n1) given, it fails to scan a namespace based on the generic device because there's no entry point in /sys/block/ for the generic device.
This patch provides two helpers to change the given generic device name to a block device name based on the instances:
ng0n1 -> nvme0n1
This patch fixes command failure:
root@vm:~/work/nvme-cli.git# nvme show-regs /dev/ng0n1
Unable to find ng0n1
get-property: Invalid argument

tree: fix generic device open failure

---

doc/meson.build
doc/update-docs.sh
src/nvme/fabrics.h

Fixes #https://github.com/linux-nvme/libnvme/issues/588

Avoid hardcoded paths in the documentation

---

src/nvme/api-types.h
src/nvme/ioctl.c
src/nvme/ioctl.h
src/nvme/mi.c
src/nvme/mi.h
src/nvme/types.h
test/mi.c

This PR is from #582 
Separation of problematic code from TP4115.
To apply TP4146 first, PR is separated.
#582 thread has comment about TP4115 problem, so #582 will be renamed as TP4115

Tp4146 only

---

src/nvme/ioctl.c

TP4146 Flexible Data Placement 2022.11.30 Ratified Command Dword 10
Bits[31:16] : Management Operation Specific (MOS)
Bits[07:00] : Management Operation (MO)

ioctl: io management send, receive args fix

---

src/nvme/fabrics.c

The ability to read from `/dev/nvme-fabrics` to find supported options is a newer Linux kernel feature added in `f18ee3d988157` (5.17-rc1). On earlier kernels, this read returns `EINVAL`,
preventing the controller from being added:
```
$ nvme discover --transport tcp --traddr 192.168.1.62
Failed to read from /dev/nvme-fabrics: Invalid argument
failed to add controller, error Invalid argument
```
So don't treat `EINVAL` as a fatal error, and instead fall back to a default set of supported options.
With this change, controllers can be created successfully:
```
$ nvme discover --transport tcp --traddr 192.168.1.62
Discovery Log Number of Records 4, Generation counter 125
...
```

fabrics: handle /dev/nvme-fabrics read failure

---

src/libnvme.map
src/nvme/private.h
src/nvme/tree.c
src/nvme/tree.h

This commit introduces a physical slot field for controller, that contains the PCI physcial slot number for controller device.

tree: Add PCI physical slot number for controller

---

src/nvme/tree.c

tree: Scan all subsystems
We need to scan all subsystems because a subsystem might show up on
different hosts, e.g 'nvme connect' with different hostnqn and the
target reports the same namespace.

tree: Scan all subsystems

---

src/nvme/fabrics.c

It's not enough to iterate over all subsystem of one host. We need to iterate over all hosts as well to find a match.

fabrics: Consider also all hosts settings for context match

---

src/libnvme.map
src/nvme/tree.c
src/nvme/tree.h
src/nvme/util.c
test/tree.c

As discussed in https://github.com/linux-nvme/libnvme/pull/695, this is a small PR to prepare for a larger PR that will introduce an improved TCP controller lookup algorithm.

tree, util: Preliminary work for improved TCP ctrl lookup 

---

src/nvme/tree.c
src/nvme/util.c
src/nvme/util.h
test/meson.build
test/mock-ifaddrs.c
test/tree.c

This PR addresses the review comments in this closed PR https://github.com/linux-nvme/libnvme/pull/695

tree: Improve tcp controller matching algorithm

---

test/tree.c

My original test case is not right. Fix this.

fix test/tree test cases

---

src/nvme/tree.c

The code could be simplified and made more readable by using early returns instead of else statements.

tree: Use early return instead of else statements

---

src/libnvme.map
src/nvme/linux.c
src/nvme/linux.h

Moved telemetry data area support detection into separate function. Added possibility to modify data transfer chunk size. Enable telemetry extraction up to specified data area.

linux: Added functions to enable faster telemetry data retrieval.

---

scripts/build.sh

Do not continue to build and hide any errors.

build: abort CI builds on first error

---

src/nvme/mi-mctp.c

If the malloc of our struct nvme_mi_transport_mctp fails, we'll attempt to free ->rsp_buf of this (now zero) pointer.
Instead, structure the error path to progressively undo the initialisation operations. This means we'll need to save the errno at the site of each possible failure.
In doing this, add a comment to the call to nvme_mi_close(), just to clarify behaviour with regards to the cleanups through that path.
Reported-by: Barnabás Pőcze <pobrn@protonmail.com>

mi-mctp: Fix free() in error path of mi_open_mctp

---

src/nvme/fabrics.c
src/nvme/linux.c

Couple more obvious alloc changes, mostly about `struct nvme_id_ctrl` and `struct nvme_id_ns`.
Received only minimal testing.

Aligned payloads allocation (continued)

---

doc/config-schema.json

Update the JSON schema with the keyring and tls_key details.

json-schema: add keyring and tls_key details

---

.checkpatch.conf
.github/workflows/checkpatch.yml

Adding new workflow to run the checkpatch.pl script from the Linux kernel.

build, CI: Add a GitHub Action to run the checkpatch.pl script

---

subprojects/json-c.wrap
subprojects/openssl.wrap

Update the two dependency to the latest upstream released one.

build: update json-c and openssl wrap

---

src/nvme/types.h

The changes for persistent event log rci print function.

types: Add persistent event log reporting context definitions

---

src/libnvme.map
src/nvme/ioctl.c
src/nvme/ioctl.h
src/nvme/linux.h
src/nvme/log.c
src/nvme/log.h

Let's cleanup some of the debugging mess and make the logging a bit better. The main cleanup is in nvme-cli though. 
I've picked up the patches from #782 for this.

Refactor and extend logging/debugging code

---

src/nvme/types.h

The changes for persistent event entry ehai print function.

types: Add PEL header additional information definitions

---

src/nvme/util.h

Fixed issue #805 for nvme_id_ns_flbas_to_lbaf_inuse().

util: Fixed nvme_id_ns_flbas_to_lbaf_inuse()

---

src/nvme/types.h

Since missed to add the documentatin.

types: Add enum nvme_csts documentation

---

src/nvme/types.h
test/register.c

Since missed to add the documentatin.

types: Add enum nvme_cap documentation

---

src/nvme/types.h

types: add the nvme Cancel command opcode

---

src/nvme/ioctl.c
src/nvme/types.h

Add enum for Protection Information Format (PIF).

types: add enum for Protection Information Format

---

src/nvme/types.h

Add the new field added in TP4141a and enums required for future implementation.

types: add new field added in TP4141a

---

.github/workflows/docs.yaml
scripts/build.sh

Build the documentation in the CI build to catch formatting issues in the submissions.
Fixes: https://github.com/linux-nvme/nvme-cli/issues/2408

build: add documentation CI build

---

doc/rst/meson.build
meson.build

Show which git version is used when configuration phase.

build: show git version used during configuration

---

src/nvme/linux.c

The original implementation for handling 'version 1' TLS PSK derivation was incomplete as the 'label' argument for the HKDF-Expand-Label functionality was not according to the spec.
Update the implementation to match the spec.
Fixes: #870

linux: update TLS version 1 PSK derivation

---

test/config/config-dump.c

Return error code from config-dump

---

src/nvme/types.h

Add the new field added in TP4142

types: add new fields added in TP4142

---

src/nvme/types.h

Adopted new fields from I/O Command Set Specific Identify Namespace Data Structure as per NVM Command Set Specification, Revision 1.1.

types: added new fields in nvme_nvme_id_ns

---

src/nvme/types.h

Added by TP4142: Temperature Threshold Hysteresis.

types: add NVME_CTRL_OAES_TTHR definition

---

src/nvme/types.h

Added enums for ANSAN and RGCNS bit of OAES field based on NVM Express Base Specification 2.1.

type: Added enums for ANSAN and RGCNS bit of OAES field

---

test/mi.c

Ensure that we're setting the `dlen` and `doff` values correctly, where the semantics of dlen in particular will change on requests vs. responses.
Passes due to the fixes in https://github.com/linux-nvme/libnvme/pull/897

tests: mi: Add test for dlen/doff values through raw admin_xfer inteface

---

src/nvme/ioctl.h
src/nvme/mi.h
src/nvme/types.h

MCDA added for Telemetry Host-Initiated Log creation
sorry for missing mi api, Just updated :)

mi: telemetry log update based NVMe v2.1

---

examples/mi-conf.c
src/nvme/mi-mctp.c

The mctp codeconstruct released the mctp APIs version 2.0 as [1]. Update code to use new APIs.
[1] https://github.com/CodeConstruct/mctp/blob/v2.0/docs/mctpd.md

Update mctp APIs to mctp codeconstruct version 2.0

---

subprojects/json-c.wrap
subprojects/openssl.wrap

Update the build dependencies.

build: bump wraps

---

src/nvme/mi.h

Since added the NVMe 2.1 log page.

mi: add nvme_mi_admin_get_log_mgmt_addr_list()

---

src/nvme/types.h
src/nvme/util.c

Added enums for missing status codes based on NVM Express Base Specification 2.1.

types,util: Added Enums for missing status codes

---

src/nvme/types.h

Update the I/O Command Set Independent Identify Namespace Data Structure fields based on NVM Express Base Specification 2.1

types: Update nvme_id_independent_id_ns fields based on NVMe 2.1 spec
